dart-lang/pana

lib/src/pub_summary.dart, lib/src/utils.dart, test/end2end/pub_server-0.1.1+3.json
@kevmoo: I'm not sure if this is really worth doing, it doesn't seem to add new information in addition to the versions we get from the pub command output parsing. On the other hand, this may be more future-proof than parsing the stdout. I'm fine either way, but I wanted to make sure this is also on the table.
=> Parse pubspec.lock and extract locked versions.

lib/src/library_analyzer.dart
Closes https://github.com/dart-lang/pana/issues/11
=> Don’t include lib/src files in package analysis

lib/src/platform.dart, test/end2end/http_data.dart, test/platform_test.dart
It looks like a nuance detail, but I think we should use standalone instead of console. My reasons:
- I was looking for a 'console icon', and I got up to date with all of the gaming consoles, but no command line icon.
- The official article refers to it as standalone: https://www.dartlang.org/tutorials/dart-vm/cmdline
=> Rename platform: console to standalone.

lib/pana.dart, lib/src/license.dart, lib/src/summary.dart, test/end2end/http_data.dart, test/end2end/pub_server_data.dart, test/license_test.dart
I think the [licensee](https://github.com/benbalter/licensee) or [detect-license](https://github.com/tantalor/detect-license/) should be used only as a fallback when we fail to detect it. We shall try to get away with trivial patterns, because:
- it is simple to do so for most use cases
- faster to execute than an external process with is own runtime baggage
- doesn't require additional setup for local development.
This CL is for the very simple patterns, we can add more as we go ahead with the package analysis, and eventually some third-party if we have many files that are not classified properly.
=> Detecting some licenses.

CHANGELOG.md, lib/src/platform.dart, pubspec.yaml, test/end2end/http_data.dart, test/end2end/pub_server_data.dart, test/platform_test.dart
Makes the values stored in JSON output much less opaque
=> Migrate `uses` values to store dart:* references directly

lib/pana.dart, lib/src/summary.dart, lib/src/summary.g.dart
Slight change of the summary.packageVersion field (non-nullable -> nullable), because there is a slight chance that a local directory is not able to identify the version, and it is better to not fail on the serialization in such cases.
=> Enable custom package directory (for direct downloads or local tests).

lib/src/analysis_options.dart
Reasons:
- `camel_case_types`: I think it is better to respect the style guide in this instance.
- `iterable_contains_unrelated_type`: high probability for errors.
- `list_remove_unrelated_type`: high probability for errors.
- `unrelated_type_equality_checks`: high probability for errors.
Most of it is coming from is coming from `stagehand` defaults (#94), and I think the rest can be ignored for now.
=> A few more linter rules for code health score.

lib/src/utils.dart
=> Don't try to run analyzer or dartfmt in directories where there are no dart files.

lib/src/package_analyzer.dart, lib/src/summary.dart
It is not self-evident from the diff, but the log.severe lines changed only the typo: `librariers` -> `libraries`.
=> Error scope in Suggestion.bug.

lib/src/code_problem.dart
Motivated by
https://analyzer-dot-dartlang-pub.appspot.com/packages/rpc/0.5.8/5655869022797824
=> Also STRONG_MODE_COULD_NOT_INFER

lib/src/maintenance.dart, test/end2end/skiplist_data.dart
We should have a separate measure for min-length if we think that's
important. As it stands, users will be confused if they see the error
when they have a (short) changelog/readme
Closes https://github.com/dart-lang/pana/issues/163
=> Remove min-length requirements for changelog and readme

lib/src/code_problem.dart, test/end2end/skiplist_data.dart
This typically happens when somebody writes an equals or compareTo with the specific type instead of the generic (or vice versa).
=> Unblock platform classification on invalid method overrides.

CHANGELOG.md, README.md, bin/pana.dart, lib/src/download_utils.dart, lib/src/package_analyzer.dart, lib/src/version.g.dart, pubspec.yaml, test/bin_pana_test.dart
#180.
While this is a breaking change, it is not breaking of the format, and the feature was never really working, hence the 0.8.0+1 version.
=> --hosted-url instead of PUB_HOSTED_URL

lib/src/analysis_options.dart, lib/src/package_analyzer.dart, lib/src/sdk_env.dart
We can fine-tune how to synchronize the linter rules between the two, I've just copied the flutter's options file as it was to unblock supermixin.
=> Flutter-specific dartanalyzer options.

CHANGELOG.md, lib/src/code_problem.dart, lib/src/package_analyzer.dart, test/end2end/skiplist_data.dart
- Fixes #194.
- Also fixes a use-case where the individual Dart files are unblocked of classification, but the package-level classification was still blocked by them.
=> Less strict plaform classification.

CHANGELOG.md, lib/src/platform.dart, test/end2end/http_data.dart, test/end2end/pub_server_data.dart, test/end2end/skiplist_data.dart, test/platform_test.dart
- addresses https://github.com/dart-lang/pub-dartlang-dart/issues/750
- removed the `everythingRemoved` part, because it is no longer used (`items` is created with filtering out the ones that work everywhere, and we are using only platform names).
=> Better messages in platform classification.

CHANGELOG.md, lib/src/pkg_resolution.dart, test/end2end/stream_broken_data.dart
Keeping some of the validation, because it could indicate issue in our output-parsing code, but the rest can cause false-alarms (because of the `dev_dependency` removal).
Closes #207.
=> Remove some of the pubspec.lock validation.

CHANGELOG.md, lib/src/license.dart, test/license_test.dart, test/licenses/mit_without_mit.txt
=> Handle MIT license without explicit 'MIT License' text.

CHANGELOG.md, lib/src/analysis_options.dart, lib/src/sdk_env.dart, test/analysis_options_test.dart
=> Ignore uri_has_not_been_generated errors.

CHANGELOG.md, lib/src/download_utils.dart, test/download_utils_test.dart
- github redirects it to raw.githubusercontent.com (or something)
- gitlab will keep serving the file with the /raw/ path segment
=> Use raw links for images in repository URLs.

CHANGELOG.md, lib/src/platform.dart, lib/src/version.g.dart, pubspec.yaml, test/platform_test.dart
The current fallback message looks weird in certain cases (mostly build-related tools without primary library):
Instead, we'd have the following:
* Platform components identified in package: `io`, `mirrors`.
=> Include component list in platform classification reasons.

CHANGELOG.md, lib/src/fitness.dart, lib/src/maintenance.dart, lib/src/messages.dart, lib/src/package_analyzer.dart, test/end2end/http_data.dart, test/end2end/pub_server_data.dart, test/end2end/skiplist_data.dart, test/end2end/stream_broken_data.dart, test/maintenance_test.dart
- Closes #262
- There is a reordering `lib/src/package_analyzer.dart`: pubspec is read earlier, moved before dartfmt run.
- Created `messages.dart` to eventually collect most of the message formatting code into one location.
=> Flutter-specific suggestion messages for dartfmt and dartanalyzer.

CHANGELOG.md, lib/src/version.g.dart, pubspec.yaml
The dartdoc/API doc coverage requires more work, and we'll need the Flutter analysis options to be released for the pub site this week.
=> Preapring 0.10.5 release

CHANGELOG.md, lib/src/pubspec.dart, test/pubspec_test.dart
=> Treat 'environment:' keys as dependent SDKs (e.g. flutter)

CHANGELOG.md, lib/src/library_scanner.dart, lib/src/package_analyzer.dart, lib/src/sdk_env.dart, lib/src/version.g.dart, pubspec.yaml
This is the first step of refactoring for #269 (among others). Running `pub global run dartdoc` requires us change back and forth between using a local and a global `PUB_CACHE`, and I would like to tidy up these runtime-related functions before implementing that.
=> Move *SDK environments into a single ToolEnvironment class.

CHANGELOG.md, lib/src/maintenance.dart, lib/src/package_analyzer.dart, lib/src/sdk_env.dart, test/end2end/skiplist_data.dart, test/end2end/stream_broken_data.dart, test/maintenance_test.dart
=> Check if dartdoc can run on the package.

CHANGELOG.md, lib/src/fitness.dart, lib/src/model.dart, lib/src/model.g.dart, lib/src/package_analyzer.dart, test/end2end/http_data.dart, test/end2end/pub_server_data.dart, test/end2end/skiplist_data.dart, test/end2end/stream_broken_data.dart, test/end2end_test.dart
#280 
At first I wanted to remove it completely, but it seems to provide some debug value of keeping it, putting it behind the new `verbose` option.
I'm also merging the `keepTransitiveLibs` option with the new `verbose` (can separate it if you'd prefer).
=> Removed Fitness.suggestions (moved/refactored)

CHANGELOG.md, lib/src/package_analyzer.dart, test/end2end/stream_broken_data.dart
It will get the false as default, and we are reporting unsuccessful dartdoc generation in the analysis, when there was no actual run of it.
=> Bugfix: do not initialize dartdocSuccessful with a value.

lib/src/library_scanner.dart, lib/src/package_analyzer.dart
There is no more need to take the `usesFlutter` parameter, nor for `ToolEnvironment` (except for the sdk path).
=> Simplify LibraryScanner constructor.

CHANGELOG.md, lib/src/package_analyzer.dart, lib/src/platform.dart, test/platform_test.dart
https://github.com/dart-lang/pub-dartlang-dart/issues/1355
Removing early platform-conflict detection, relying on a more detailed report.
=> Better expose platform conflict reasons.

lib/src/fitness.dart
The current `package:test` analysis has a "null" string in it, this fixes it.
=> Fix 'null' text in platform conflict descriptions.

.travis.yml
Tests are passing with and without Dart2 Preview flags.
=> Upgrade CI to dev.63 SDK

lib/src/package_analyzer.dart, test/end2end/skiplist-0.1.0.json
It works for bignum the same way (referenced in https://github.com/dart-lang/pub-dartlang-dart/issues/1395)
=> Override platform classification when code quality is low.

lib/src/model.dart, lib/src/model.g.dart, test/end2end/fs_shim-0.7.1.json, test/end2end/http-0.11.3-13.json, test/end2end/pub_server-0.1.1-3.json, test/end2end/skiplist-0.1.0.json, test/end2end/stream-0.7.2-2.json, test/end2end_test.dart
As the pub site will do dartdoc coverage report and scoring outside of `pana`, there is no need to run the tests with `dartdoc`.
The flag and option should eventually be removed (in a future breaking release).
=> Don't run dartdoc in end2end tests.

CHANGELOG.md, lib/src/maintenance.dart, lib/src/model.dart, lib/src/platform.dart, test/end2end/fs_shim-0.7.1.json, test/end2end/http-0.11.3-13.json, test/end2end/pub_server-0.1.1-3.json, test/end2end/skiplist-0.1.0.json, test/end2end/stream-0.7.2-2.json, test/maintenance_test.dart
Updated platform classification:
* Library conflict rule is moved to the end of the evaluation.
* Top file-related suggestions are directly exposed.
* The bulk summary suggestion is more compact.
Handles https://github.com/dart-lang/pub-dartlang-dart/issues/1355 the following way:
- `package:test` will be classified as `flutter`, and `other`
- The library conflict will be visible in the suggestion list with heavy (20%) penalty.
With that, the overall score remains the same, but the package will have a valid platform list, and it will be clear why its maintenance score is penalized.
=> Platform classification: more exposed, less blocked.

CHANGELOG.md, lib/src/fitness.dart, lib/src/maintenance.dart, lib/src/messages.dart, lib/src/model.dart, lib/src/package_analyzer.dart, lib/src/version.g.dart, pubspec.yaml, test/end2end/dartdoc-0.20.0.json, test/end2end/fs_shim-0.7.1.json, test/end2end/http-0.11.3-13.json, test/end2end/pub_server-0.1.1-3.json, test/end2end/skiplist-0.1.0.json, test/end2end/stream-0.7.2-2.json, test/maintenance_test.dart
- `dartanalyzer` suggestions become one per file, with the summary issue count included
- `maintenance` needed to be adjusted to handle the now-reduced suggestions per file
=>  Updated report on dartanalyzer suggestions.

CHANGELOG.md, lib/src/package_analyzer.dart, lib/src/sdk_env.dart, test/end2end/dartdoc-0.20.0.json
- `flutter format` emits different output and doesn't communicate with exit codes
- kept the same structure of per-directory scanning
- fixed a small bug with the non-Flutter code path where an empty `bin` directory would have ignored the `lib` entirely.
- https://github.com/dart-lang/pub-dartlang-dart/issues/1484
=> Use flutter format instead of dartfmt for Flutter packages.

CHANGELOG.md, lib/src/health.dart, lib/src/model.dart, lib/src/version.dart, pubspec.yaml, test/end2end/dartdoc-0.20.3.json, test/end2end/http-0.11.3-17.json, test/end2end/stream-2.0.1.json
An alternative to https://github.com/dart-lang/pana/pull/414
The tradeoff here is:
- the impact of the score is not adjusted (the calculation is simpler),
- the sum of the individual penalties is larger than the overall penalty,
- there is no dependency on the order of the suggestions, it is symmetrical, and does not change if 1 out of N issues get fixed.
=> Estimate health score penalties.

CHANGELOG.md, README.md, lib/src/maintenance.dart, lib/src/model.dart, lib/src/utils.dart, test/utils_test.dart
There is a small, but growing portion of packages that use non-English description (and readme) to describe what the package does (e.g. [work](https://pub.dartlang.org/packages/work) or [tencent_cos](https://pub.dartlang.org/packages/tencent_cos)). We shall encourage using English, and this is a good proxy for it.
=> Penalty for description using too many non-ASCII characters.

CHANGELOG.md, lib/src/sdk_env.dart
- the use of `--dry-run` changes the flutter output format, it is now the same as `dartfmt`
- however, the exit codes differ
- we still can't use `--dry-run` with machine-readable output (filed https://github.com/dart-lang/sdk/issues/34961 to track it)
=> Use --dry-run on executing flutter format.

bin/pana.dart
Local package analysis (`--source path`) did not get the `--flutter-sdk` parameter, nor the analysis options (verbosity, pub hosted path).
=> Fix command-line consistency issues.

CHANGELOG.md, lib/src/sdk_env.dart
=> Use Flutter's internal Dart SDK to run dartanalyzer on Flutter packages.

test/end2end/dartdoc-0.24.1.json, test/end2end/stream-2.0.1.json
`package:analyzer` has new files and the test fails without them.
=> Fix CI tests.

CHANGELOG.md, lib/src/package_analyzer.dart
The log message usually happens when a package gets analyzed, but the sources are incompatible with the current tooling. In such cases an exception will be thrown anyway (which gets logged at a different place), and the output will be an empty string, which makes this particular logging statement useless.
=> Remove 'Bad input?' log message.

CHANGELOG.md, lib/src/analysis_options.dart, lib/src/version.dart, pubspec.yaml, test/analysis_options_test.dart
This is a follow-up for #458. The two extra options are now part of the stagehand-generated default project template.
=> Update analysis options: cancel_subscriptions and test_types_in_equals.

lib/src/download_utils.dart
It is unlikely that this is related to https://github.com/dart-lang/pub-dartlang-dart/issues/1868, but making sure that we don't have any leftover from the download hanging there.
=> Delete temp directory in case download fails.

CHANGELOG.md, README.md, lib/src/maintenance.dart, lib/src/package_analyzer.dart, lib/src/pubspec.dart, lib/src/sdk_env.dart, test/end2end/syntax-0.2.0.json
- lenient parsing in Pubspec and extra exception guard in tool_env (e.g. to cover for deep parsing issues)
- 100% penalty for strict parsing errors
https://github.com/dart-lang/pub-dartlang-dart/issues/1960
=> Lenient and strict parsing of pubspec.yaml

CHANGELOG.md, lib/src/analysis_options.dart, lib/src/pkg_resolution.dart, lib/src/sdk_env.dart, test/analysis_options_test.dart, test/end2end/angular_components-0.10.0.json, test/end2end/dartdoc-0.24.1.json, test/end2end/http-0.11.3-17.json, test/end2end/pub_server-0.1.4-2.json, test/end2end/stream-2.0.1.json
Fixes #459.
We need to add `package:pedantic` in the `dev_dependencies`, and subsequently remove it from the list of resolved packages (unless it is referenced in the original `pubspec.yaml`).
=> Use package:pedantic as default package analysis ruleset.

CHANGELOG.md, lib/src/model.dart, lib/src/package_analyzer.dart, lib/src/version.dart, pubspec.yaml
`pedantic` introduced way more hints, and in a few rare cases these now prevent platform classification. I think we should allow these to slip, and still do the classification if there are not too many errors or warnings.
=> Don't block platform classification on hints.

CHANGELOG.md, lib/src/sdk_env.dart, lib/src/utils.dart
=> Deduplicate dartanalyzer output lines, and increase timeout.

CHANGELOG.md, lib/src/analysis_options.dart, lib/src/sdk_env.dart, lib/src/version.dart, pubspec.yaml, test/analysis_options_test.dart
The new method and the test also ensures that we detect if another upgrade breaks it.
=> Fixed the use of pedantic rules following the new versioned pattern.

README.md, bin/pana.dart, test/bin_pana_test.dart
@jonasfj: I've updated the references in the CLI help too, but that is debatable, as the pub client will continue to use `pub.dartlang.org`...  or will the new version use `pub.dev` and we keep supporting the old ones on the old domain?
=> Update references to pub.dev site.

CHANGELOG.md, README.md, lib/src/maintenance.dart, lib/src/model.dart, lib/src/package_analyzer.dart, lib/src/version.dart, pubspec.yaml, test/end2end/angular_components-0.10.0.json, test/end2end/dartdoc-0.24.1.json, test/end2end/stream-2.0.1.json, test/maintenance_test.dart
Fixes https://github.com/dart-lang/pub-dev/issues/2319
=> Penalize package constraints that does not support the latest published versions of their dependencies.

CHANGELOG.md, README.md, lib/src/maintenance.dart, lib/src/version.dart, pubspec.yaml, test/end2end/angular_components-0.10.0.json, test/end2end/dartdoc-0.24.1.json, test/end2end/pub_server-0.1.4-2.json
https://github.com/dart-lang/pub-dev/issues/2380
=> Fix: penalize outdated package constraints only for direct dependencies.

lib/src/license.dart, test/end2end/angular_components-0.10.0.json, test/end2end/dartdoc-0.24.1.json, test/end2end/http-0.11.3-17.json, test/end2end/pub_server-0.1.4-2.json, test/end2end/stream-2.0.1.json
- Fixes CI tests (which auto-upgrades the dependencies including `package:analyzer`).
- We can't upgrade to 0.37.0 yet because json_serializable does not support it yet.
=> Update end2end tests to match analyzer 0.36.4

.travis.yml, test/end2end/angular_components-0.10.0.json, test/end2end/dartdoc-0.24.1.json, test/end2end/http-0.11.3-17.json
Looks like we are getting an extra sentence in all the `DEPRECATED_MEMBER_USE` reported by the `dartanalyzer`.
=> Upgrade CI to 2.6.0

CHANGELOG.md, lib/src/model.dart, test/end2end/angular_components-0.10.0.json, test/pub_summary_test.dart
- fixes #572 
- end2end test confirmed fix on [angular_components 0.10.0](https://pub.dev/packages/angular_components/versions/0.10.0#-analysis-tab-)
=> Fix: pre-release versions are not considered when detecting outdated dependencies.

CHANGELOG.md, lib/src/tag_detection.dart, lib/src/version.dart, pubspec.yaml, test/end2end/angular_components-0.10.0.json
- Fixes #591.
- Top-level libraries are the files in `lib/*.dart`. However, if there is a primary library in the package (`/lib/[package_name].dart`), it will be used as a single value in top-level libraries.
- Tags are added when all of the top-level libraries agree on supporting the given SDK or platform.
- Binary-only packages are handled via a temporary heuristic.
=> Updated tag detection for packages without a primary library.

CHANGELOG.md, pubspec.yaml
(`json_serializable`'s codegen is no longer blocked on it)
=> Upgrade package:analyzer dependency.

CHANGELOG.md, lib/src/tag_detection.dart, test/tag_detection_external_test.dart
- fixes #594
- `cli` and `nativewrappers` in `dart/native-jit` (not sure if aot is the same, is it?).
- `html_commons` in `dart/web`.
- added a test that downloads the SDK-provided definitions and checks them against our definitions
=> More dart:* libraries in tag detection.

CHANGELOG.md, lib/src/analysis_options.dart, lib/src/package_analyzer.dart, lib/src/sdk_env.dart, lib/src/version.dart, pubspec.yaml, test/analysis_options_test.dart
The default behaviour remains the current one, but we can control it for pub.dev without modifying it in `pana` for each new ruleset.
=> Control the linter rule set via InspectOptions.

CHANGELOG.md, lib/src/tag_detection.dart, lib/src/version.dart, pubspec.yaml
=> Use lib/**/*.dart as top-level libraries when there is no lib/*.dart

CHANGELOG.md, lib/src/code_problem.dart, lib/src/package_analyzer.dart, test/code_problem_test.dart
- added fix to parse files (https://github.com/dart-lang/pub-dev/issues/3389)
- added sanity check + log to detect if we are missing out on other patterns
=> Unescape double-backslash on Windows

CHANGELOG.md, lib/src/sdk_env.dart, lib/src/version.dart, pubspec.yaml, test/sdk_env_test.dart
It may contain a date, which needs to be considered in the parser
Fixes https://github.com/dart-lang/pana/issues/628
Prepare for v0.13.7
=> Handle new output from --version in latest Dart SDK

test/bin_pana_test.dart, test/end2end_test.dart, test/golden_file.dart, test/goldens/end2end/angular_components-0.10.0.json, test/goldens/end2end/dartdoc-0.24.1.json, test/goldens/end2end/http-0.11.3-17.json, test/goldens/end2end/pub_server-0.1.4-2.json, test/goldens/end2end/stream-2.0.1.json, test/goldens/help.txt
https://github.com/dart-lang/pana/pull/653 was broken, but because the files were not checked in, it did not show up on travis. This should not be able to happen again.
=> Fix golden paths. Fail test if golden file was recreated

lib/src/tag_detection.dart, test/goldens/end2end/dartdoc-0.24.1.json, test/goldens/end2end/http-0.11.3-17.json, test/goldens/end2end/pub_server-0.1.4-2.json, test/tag_detection_test.dart
'Package not compatible with runtime flutter-native on android' reads better than 'Package not compatible with runtime flutter-native of android'
=> Improve sentence

lib/src/create_report.dart, lib/src/package_analyzer.dart, lib/src/package_context.dart
- On pub.dev we provide an instance with caching.
- Moved to the `PackageContext` as it will also hold the license file (and could use it for the licenseUrl calculation)
=> Use the analyzer-provided UrlChecker in the createReport() checks.

lib/src/create_report.dart, lib/src/package_context.dart, test/goldens/end2end/fs_shim-0.7.1.json, test/goldens/end2end/fs_shim-0.7.1.json_report.md, test/goldens/end2end/skiplist-0.1.0.json, test/goldens/end2end/skiplist-0.1.0.json_report.md
- This is a refactor preparing for implementing https://github.com/dart-lang/pub-dev/issues/3854
- It also removes the phrase "latest stable" Dart SDK, instead using the "current".
=> Consistent message for SDK constraint issue.

pubspec.yaml
These are used by https://github.com/dart-lang/pana/pull/830 but only existed as transitive dependencies.
=> Add missing dependencies

CHANGELOG.md, lib/src/dartdoc_analyzer.dart
This will replace https://github.com/dart-lang/pub-dev/blob/master/app/lib/dartdoc/dartdoc_runner.dart#L670-L684 in pub-dev.
=> Changing signature of dartdocFailedSection to match pub.dev

CHANGELOG.md, README.md, bin/pana.dart, test/goldens/help.txt
- `dart-sdk` is useful to run a test with a different SDK and is a pair for `flutter-sdk`
- `exit-code-threshold` fixes #843.
=> New command-line args.

lib/src/download_utils.dart
- #879
- pub.dev should have a cache that stores the URLs that can be accessed successfully.
- The cache could have a longer timeout (e.g. 7 days).
- If a URL is not accessible, it doesn't become a negative cached entry, it would be tried via `super.exists()` and on success the status could be stored in cache.
=> UrlChecker.exists to enable a caching hook for pub.dev

CHANGELOG.md, lib/src/create_report.dart
=> Limit the length of the source spans in the report.

CHANGELOG.md, analysis_options.yaml, lib/src/create_report.dart, lib/src/license.dart, lib/src/model.dart, lib/src/pkg_resolution.dart, lib/src/pubspec.dart, lib/src/sdk_env.dart, pubspec.yaml, test/create_report_test.dart, test/end2end_test.dart
Migrates to the `recommended` set of lints from https://pub.dev/packages/lints, removes duplicate linter rules, and fixes the corresponding issues.
=> Migrate to recommended lints

CHANGELOG.md, lib/src/package_analyzer.dart
- #895
- I think this is a better solution than `path` rewrites, as it doesn't need to change the `pubspec.yaml` at all.
=> Detect git monorepo root and copy everything from that root for local analysis

pubspec.yaml
Error when publishing:
```
Package validation found the following errors:
* line 82, column 1 of lib/src/tag_detection.dart: This package does not have meta in the `dependencies` section of `pubspec.yaml`.
╷
82 │ import 'package:meta/meta.dart';
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
* line 10, column 1 of lib/src/create_report.dart: This package does not have meta in the `dependencies` section of `pubspec.yaml`.
╷
10 │ import 'package:meta/meta.dart';
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
```
=> Added meta dependency

CHANGELOG.md, lib/src/tag/_common.dart, lib/src/tag/tagger.dart, test/tag/tag_null_safe_test.dart
- Fixes  #918.
- Adds more details for #891 into the report section.
=> Fix null-safety classification issue with dart-ext: imports.

bin/pana.dart
Hi,
I finally got around to trying the fix for [this issue I reported a while back](https://github.com/dart-lang/pana/issues/843) and found a small problem with it. I want to be able to specify zero tolerance for any lost points, but the code requires I set the exit threshold to at least 1 (0 is ignored). This PR fixes that.
=> Allow zero tolerance

test/bin_pana_test.dart
Fixes a test that is failing on Windows due to line endings not being normalized correctly.
=> Normalize line endings in test

CHANGELOG.md, lib/src/utils.dart
- I think one of the core reasons we have incomplete dartdoc reports may be the lack of kill signal.
- https://github.com/dart-lang/pub-dev/issues/4750
=> Terminate the timeouted processes with sigkill.

CHANGELOG.md, lib/src/sdk_env.dart, lib/src/utils.dart
The SDK issue has been fixed a long time ago.
=> runProc's deduplicate parameter is no longer used and will be ignored.

CHANGELOG.md, lib/src/download_utils.dart, lib/src/license.dart, lib/src/report/template.dart
I'd like to have redis-based URL status caching on pub.dev, and the current methods do not provide a way to cache the missing status, instead it will be retried every time. 
Also: added `flutter.dev` in the default list of internal urls.
=> Rewrite of UrlChecker and UrlStatus.

CHANGELOG.md, lib/src/sdk_env.dart, lib/src/utils.dart, test/sdk_env_test.dart
- #941
- Throw `FormatException` when SDK version parsing fails.
- Read both `stdout` and `stderr`, as newer SDKs switched to `stdout`.
=> Fix SDK version parsing issue.

CHANGELOG.md, lib/src/download_utils.dart, lib/src/model.dart, lib/src/model.g.dart, lib/src/package_analyzer.dart, lib/src/package_context.dart, lib/src/report/template.dart, test/download_utils_test.dart, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json, test/goldens/end2end/async-2.5.0.json, test/goldens/end2end/audio_service-0.17.0.json, test/goldens/end2end/bulma_min-0.7.4.json, test/goldens/end2end/dnd-2.0.0.json, test/goldens/end2end/http-0.13.0.json, test/goldens/end2end/lints-1.0.0.json, test/goldens/end2end/mime_type-0.3.2.json, test/goldens/end2end/sdp_transform-0.2.0.json, test/goldens/end2end/skiplist-0.1.0.json, test/goldens/end2end/url_launcher-6.0.3.json, test/goldens/end2end/webdriver-3.0.0.json
- https://github.com/dart-lang/pub-dev/issues/4902
- Only URLs with problems are stored (assuming it will be the rare case).
- URLs in `README.md` and `CHANGELOG.md` could also go into this list (in a future change).
- Tested with `random_names`, I wouldn't put it to the end2end list for now, I'd rather look for a package that has a problem in their readme.
=> Track and store URL problems in the Summary.

CHANGELOG.md, lib/src/package_context.dart, lib/src/sdk_env.dart, lib/src/utils.dart, test/self_run_test.dart
- Fixes #966.
- Creates an extended `ProcessResult` class for the additional information of timeout or output exceeded.
=> Better handling of `runProc` timeout or output exceeded errors.

CHANGELOG.md, lib/src/tag/_graphs.dart, lib/src/tag/_violations.dart
This helps to unblock analysis on bugs like #914: the URI of the source code is exposed in the report, the exception is logged with stacktrace and warning, and we will no longer display a forever-awaiting status on packages like that (e.g. `wialon 1.0.1+1`).
=> Fail gracefully on source code parsing bugs.

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
Also upgrading `json_annotation`, as the build message seemed to insist on a new range.
=> Upgrade package:analyzer dependency constraint.

CHANGELOG.md, lib/src/download_utils.dart, lib/src/repository_url.dart, test/repository_url_test.dart
- reusing and repurposing the tests for the now-defunct `getRepositoryUrl`
=> Formalized repository URL parsing and resolving.

README.md
Also removed the leading `> ` as it only makes copying annoying
=> Remove deprecated `pub` usage in readme

lib/src/report/static_analysis.dart, test/report/static_analysis_test.dart
=> Fix source span on CR characters.

CHANGELOG.md, lib/src/model.dart, lib/src/model.g.dart, lib/src/package_analyzer.dart, lib/src/repository/check_repository.dart, test/end2end_test.dart, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json, test/goldens/end2end/async-2.5.0.json, test/goldens/end2end/audio_service-0.17.0.json, test/goldens/end2end/bulma_min-0.7.4.json, test/goldens/end2end/dnd-2.0.0.json, test/goldens/end2end/http-0.13.0.json, test/goldens/end2end/mime_type-0.3.2.json, test/goldens/end2end/nsd_android-1.0.2.json, test/goldens/end2end/sdp_transform-0.2.0.json, test/goldens/end2end/skiplist-0.1.0.json, test/goldens/end2end/url_launcher-6.0.3.json, test/goldens/end2end/webdriver-3.0.0.json
- next step: extend this data with the verification that the link to the repository is indeed the package itself
- optional items to store here: repo type (e.g. git), provider (e.g. github), git tags info... (TBD)
- end2end tests are enabled to check the git remote
- pub.dev may need to have a cache for the default git branch (TBD)
=> Expose repository info in Summary.

CHANGELOG.md, lib/src/report/dependencies.dart, lib/src/version.dart, pubspec.yaml
Passing the empty string to `Uri.tryParse` results in an empty string. Hence we ended up calling getVersionListing with a wrong value for `pubHostedUrl`.
=> Fix computation of 'pubHostedUrl' in 'computeOutdatedVersions'.

CHANGELOG.md, lib/src/repository/check_repository.dart, lib/src/repository/git_local_repository.dart, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json, test/goldens/end2end/audio_service-0.17.0.json, test/repository/git_local_repository_test.dart
- Better error message if the path does not have `pubspec.yaml`.
- TBD later: checking file names, and also checking other `pubspec.yaml` files under the specified path.
=> List files and detect the presence of pubspec.yaml during repository verification.

CHANGELOG.md, lib/src/repository/check_repository.dart, lib/src/repository/git_local_repository.dart, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json, test/goldens/end2end/async-2.5.0.json, test/goldens/end2end/audio_service-0.17.0.json, test/goldens/end2end/nsd_android-1.0.2.json, test/goldens/end2end/url_launcher-6.0.3.json
- detects if multiple `pubspec.yaml` has the same package name, which may be a copy-paste error or a fraud attempt
- exposes the matched package path in the result data
=> Check all pubspec.yaml during repository verification.

CHANGELOG.md, lib/src/sdk_env.dart, test/goldens/end2end/audio_service-0.18.4.json, test/goldens/end2end/audio_service-0.18.4.json_report.md, test/goldens/end2end/sdp_transform-0.2.0.json, test/goldens/end2end/sdp_transform-0.2.0.json_report.md, test/goldens/end2end/url_launcher-6.1.2.json, test/goldens/end2end/url_launcher-6.1.2.json_report.md
- Fixes #1069.
- Re-implements part of #1052, without the actual reuse (which should be a separate PR).
=> Use the stripped/augmented pubspec.yaml for 'pub outdated'

lib/src/code_problem.dart, test/code_problem_test.dart
- Fixes #1081 (at least the part which we have control over).
- The `ToolException` is better than `ArgumentError`, as it becomes part of the pana report (while it is also being logged), without blocking the rest of analysis too much.
=> Use ToolException instead of ArgumentError in analysis output processing.

CHANGELOG.md, lib/src/model.dart, lib/src/model.g.dart, lib/src/repository/check_repository.dart, lib/src/repository/repository_url.dart, test/goldens/end2end/async-2.5.0.json, test/goldens/end2end/audio_service-0.18.4.json, test/goldens/end2end/bulma_min-0.7.4.json, test/goldens/end2end/dnd-2.0.0.json, test/goldens/end2end/http-0.13.0.json, test/goldens/end2end/mime_type-0.3.2.json, test/goldens/end2end/nsd_android-1.2.0.json, test/goldens/end2end/sdp_transform-0.2.0.json, test/goldens/end2end/skiplist-0.1.0.json, test/goldens/end2end/url_launcher-6.1.2.json, test/goldens/end2end/webdriver-3.0.0.json
This will be needed for URL rewrite rules (we shouldn't even try to rewrite URLs that are not known providers).
=> Expose 'RepositoryProvider' in the analysis result ('Repository.provider')

lib/src/tag/tagger.dart
Windows uses the `\` path separator
=> correct path filtering to work with windows path separators

CHANGELOG.md, lib/src/repository/repository_url_resolver.dart, lib/src/version.dart, pubspec.yaml, test/repository/repository_url_test.dart
- Fix: do not strip query parameters.
- Fix: GitHub relative and absolute links (without scheme and host name) must be inside the repository.
- Fix: unknown providers may not use `branch` in the final URL path.
- New feature: `relativeFrom` parameter to indicate the source of the references (e.g. `example/README.md`)
- Added missing tests for unknown providers.
=> Improved URL resolver.

pubspec.yaml
The [usage](https://github.com/dart-lang/pana/blob/903a15ff305369d17a54d1f4aa4ae0add79acbd0/lib/src/pubspec.dart#L46) of the screenshots field stipulates at least v1.2.0 of package:pubspec_parse - see https://github.com/dart-lang/pubspec_parse/commit/47fa52db323ff3a3315c4462756e38a7020cb91d
=> Bump version constraint of pubspec_parse

CHANGELOG.md, lib/src/repository/git_local_repository.dart
- Fixes https://github.com/dart-lang/pana/issues/1095.
- Replaces #1097.
=> Always use English locale for git commands.

CHANGELOG.md, lib/src/sdk_env.dart
=> Remove 'pubspec_overrides.yaml' when running 'pub upgrade' or 'pub outdated'.

pubspec.yaml
The [usage](https://github.com/dart-lang/pana/blob/efcfd1d8e917900817a8fd72bf16c795ab508a96/lib/src/download_utils.dart#L39) of the `RetryClient` class (imported from `package:http/retry.dart`) stipulates at least v0.13.2 of `package:http`
- see https://github.com/dart-lang/http/commit/69d6064dd92470ed7ccd50a808fc789ee7716fe8 where it was moved from `package:http_retry`
- also see https://github.com/dart-lang/http/blob/master/pkgs/http/CHANGELOG.md#0132
=> bump version constraint of package:http

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- added CHANGELOG entries
- bumped version constraint for `json_annotation` (was a warning from build_runner)
- bumped release version
=> Prepare release: 0.21.16

CHANGELOG.md, lib/src/license.dart, lib/src/license_detection/license.dart, lib/src/license_detection/token_matcher.dart, test/licenses/isc_license_test.dart
- Fixes #1071.
- The current code produced a high score, but not enough to cross the threshold. Removing the known patterns from all the licenses (both the patterns and the input in question) should increase the confidence for all kind of licenses.
- Also did small cleanups as I was debugging the code.
=> License text preprocessing to detect ISC license.

CHANGELOG.md, lib/src/tag/tagger.dart
=> Do not check dart: libraries in null-safety tagger.

lib/src/model.dart
This was a leftover artifact (when I created the PR to check the potential uses).
=> Remove 'required' from AnalysisResult's contributingUrl.

CHANGELOG.md, lib/src/tag/_common.dart, lib/src/tag/_specs.dart, lib/src/tag/_violations.dart, lib/src/tag/tagger.dart
The top-level tagging methods with `List<String> tags, List<Explanation> explanations` could be moved to use `TaggingResult` as the next step.
=> New platform tagging with separate Dart and Flutter runtimes.

CHANGELOG.md, lib/src/sdk_env.dart
- Follow-up to #1158.
- When running the analysis with the future Flutter SDK, we'll need to also set the FLUTTER_ROOT to the correct directory, otherwise on pub-dev it would use the stable's path.
=> Set FLUTTER_ROOT environment variable when running flutter commands.

CHANGELOG.md
we can have changed it to code highlighting
=> Fix: revert the extra line in <summary> blocks

bin/pana.dart, lib/src/package_analyzer.dart, lib/src/sdk_env.dart
Explicitly suppress analytics when invoking dart and flutter from pana.
This should already happen if pana is invoked with a ToolEnvironment with a 'CI=1' in the environment.
This PR also passes the surrounding environment into the subprocesses when bin/pana.dart is invoked.
=> Don't send analytics

lib/src/pubspec.dart, test/pubspec_test.dart
Fix of https://github.com/dart-lang/pub-dev/issues/6305
=> Allow dart 2 compatible packages to be future compatible

lib/src/download_utils.dart
[buymeacoffee.com](https://www.buymeacoffee.com/) doesn't like when the user agent contains the substring "git".
They suggested that we change the user agent.
```
> curl --head https://www.buymeacoffee.com/ -A git
HTTP/2 403 
date: Fri, 06 Jan 2023 08:46:57 GMT
content-type: text/plain; charset=UTF-8
content-length: 16
x-frame-options: SAMEORIGIN
referrer-policy: same-origin
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=hi%2Bg06I0cyl3vHpArxLQkQqVb5aWHCT4h%2BGBptu9rrW1lVYsvMaEs1gdy0PHfaObpqiPVQ11GyPwwVNTwpWZw00gm0l0O1C4QvVnumMPYUzo9uAFC2%2BTxqyidRL5gaaoFzzxMNjw"}],"group":"cf-nel","max_age":604800}
nel: …
```
=> Use different user agent for url checks

lib/src/report/documentation.dart, test/screenshot_test.dart
This makes the build green again.
We should probably list all the files once, and do the same for all our file checks (readme, changelog...)
=> Make example-detection work on case-preserving file systems

CHANGELOG.md, lib/src/sdk_env.dart, lib/src/version.dart, pubspec.yaml
`_futureFlutterSdkDir` is redundant and could have been misused, better to use one of the `_FlutterSdk`s.
=> Code cleanup in ToolEnvironment

CHANGELOG.md, lib/src/repository/check_repository.dart, lib/src/repository/git_local_repository.dart, test/repository/git_local_repository_test.dart
- This is one option to fix #1200, by allowing it to continue when the path is not accepted.
- (Please review the alternative too: #1233 .)
=> Do not block repository check when `pubspec.yaml` is in path that is not accepted.

CHANGELOG.md, analysis_options.yaml, lib/src/analysis_options.dart, lib/src/package_analyzer.dart
- #1229
- `pub.dev` provides the file content via `InspectOption`, which is looked up the same way as done here.
- maybe we can also add a hardcoded content as a fallback instead of the GitHub fetch (and verify it is up-to-date via test)
=> Resolve lints/core.yaml if available locally, deprecate inspect option.

CHANGELOG.md, lib/src/model.dart, lib/src/model.g.dart, lib/src/package_analyzer.dart, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json, test/goldens/end2end/async-2.11.0.json, test/goldens/end2end/audio_service-0.18.10.json, test/goldens/end2end/bulma_min-0.7.4.json, test/goldens/end2end/dnd-2.0.1.json, test/goldens/end2end/http-0.13.0.json, test/goldens/end2end/lints-1.0.0.json, test/goldens/end2end/mime_type-0.3.2.json, test/goldens/end2end/nsd_android-1.2.2.json, test/goldens/end2end/onepub-1.1.0.json, test/goldens/end2end/sdp_transform-0.2.0.json, test/goldens/end2end/skiplist-0.1.0.json, test/goldens/end2end/steward-0.3.1.json, test/goldens/end2end/url_launcher-6.1.12.json, test/goldens/end2end/webdriver-3.0.0.json
While we could always calculate it on the fly from the report, we may want to load and cache the `Report` and the `AnalysisResult` separately. Part of #1229.
=> Store scores on AnalysisResult

CHANGELOG.md, lib/src/package_analyzer.dart, lib/src/package_context.dart, lib/src/report/static_analysis.dart, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json_report.md, test/goldens/end2end/bulma_min-0.7.4.json, test/goldens/end2end/bulma_min-0.7.4.json_report.md, test/goldens/end2end/mime_type-0.3.2.json, test/goldens/end2end/mime_type-0.3.2.json_report.md, test/goldens/end2end/sdp_transform-0.2.0.json, test/goldens/end2end/sdp_transform-0.2.0.json_report.md, test/goldens/end2end/skiplist-0.1.0.json, test/goldens/end2end/skiplist-0.1.0.json_report.md
Fixes issues like the following score page:
=> Fix: static analysis is done only when the package resolution was successful.

CHANGELOG.md, lib/src/dartdoc/index_to_pubdata.dart, lib/src/version.dart, pubspec.yaml
Copy of the code from https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_dartdoc/lib/pub_data_generator.dart#L91-L97
=> Limit the number of exported documentation entries on pub-data.json.

CHANGELOG.md, lib/src/tag/_specs.dart
Fixes https://github.com/dart-lang/pana/issues/1285
---
=> Add js_interop_unsafe as a web library

CHANGELOG.md, lib/src/dartdoc/dartdoc.dart, lib/src/dartdoc/index_to_pubdata.dart, lib/src/dartdoc/pub_dartdoc_data.dart, lib/src/dartdoc/pub_dartdoc_data.g.dart
- Fixes the edge case of #1282, where a large but overall under-documented package removes some documentation which may be reported as missing.
- It also enables the separation of entries data (part of a long-term refactoring of pub-data.json to better fit the indexing).
=> Pre-compute missing documentation symbol before pruning the results.

CHANGELOG.md, lib/src/dartdoc/dartdoc_index.dart, lib/src/dartdoc/index_to_pubdata.dart, lib/src/dartdoc/pub_dartdoc_data.dart, lib/src/dartdoc/pub_dartdoc_data.g.dart, test/end2end_test.dart, test/goldens/end2end/url_launcher-6.1.12.json, test/goldens/end2end/url_launcher-6.1.12.json_report.md
- the last part of #1273 (before complete removal)
- uses the same logic as https://github.com/dart-lang/pana/blob/master/lib/src/dartdoc/dartdoc_index.dart#L99-L100
=> Deprecate the use of 'kind' in pub-data.json.

CHANGELOG.md, lib/src/dartdoc/index_to_pubdata.dart, lib/src/version.dart, pubspec.yaml, test/goldens/end2end/async-2.11.0.json, test/goldens/end2end/async-2.11.0.json_report.md, test/goldens/end2end/dnd-2.0.1.json, test/goldens/end2end/dnd-2.0.1.json_report.md, test/goldens/end2end/url_launcher-6.1.12.json, test/goldens/end2end/url_launcher-6.1.12.json_report.md
=> Don't report hidden constructors as undocumented API symbols.

lib/src/package_context.dart, lib/src/report/documentation.dart
- Remove the reference of the process result, as it is not used later.
- Non-nullability resolves the ambiguity of the null return value.
- Explicit error message if the expected output files are missing (while the process otherwise completed).
=> Always non-nullable DartdocResult.

CHANGELOG.md, lib/src/tool/run_constrained.dart
- We don't use the bytes output, only the `asString`, no need to keep the API method of it around. (We may re-add later if needed.)
- Also fixes decoding of the chunked bytes (which may be broken on non-aligned byte boundaries).
=> Remove ProcessOutput.asBytes

CHANGELOG.md, bin/pana.dart, lib/src/package_analyzer.dart, lib/src/references/pubspec_urls.dart, lib/src/repository/check_repository.dart, test/end2end_test.dart
Removing the option as we always want to verify the repository. (Maybe we want to separate it by network-using and restricted parts, but that may come in a later version).
Code change is largely indent after removing the `if (sharedContext.options.checkRemoteRepository) {` block.
=> Always verify repository as part of the analysis.

lib/src/screenshots.dart
- Fixes a tiny bug on the old file's line 382: it returned the previous process result's exit code instead the current one.
- Reducing the process result's use to prepare for future changes in `runProc`.
=> Refactor screenshot processing: reduce reliance on full process result.

CHANGELOG.md, lib/src/package_context.dart, lib/src/sdk_env.dart, lib/src/tool/run_constrained.dart, pubspec.yaml
- using `RetryOptions` from `package:retry` as part of the API
- breaking change in `ToolException`: storing the entire process result instead of just the `stderr`.
=> Merge _retryProc into runConstrained.

CHANGELOG.md, lib/src/report/dependencies.dart, lib/src/sdk_env.dart, test/goldens/end2end/http-0.13.0.json
- Fixes an unrelated CI test failure.
- Moves the environment field into the Dart/Flutter SDK entity. (Precursor to also have the HOME directory be specific to an SDK).
=> Refactor environment handling in ToolEnvironment.

CHANGELOG.md, lib/src/package_context.dart, lib/src/sdk_env.dart
- `'--no-validate-links'` in `dartdoc()` is always set anyway, no need to keep the optional parameter (similarly the other parameters are never set, we can remove them).
- removing further methods that are never called or restringing the visibility of them (`_getFlutterVersion()`).
=> Remove some methods and method parameters from ToolEnvironment.

CHANGELOG.md, bin/pana.dart, lib/src/package_analyzer.dart, lib/src/sdk_env.dart, test/end2end_light_test.dart, test/end2end_test.dart
- Removing `PackageAnalyzer.create` as it has very little benefit over `ToolEnvironment.create`.
- Consolidated `environment` handling in `ToolEnvironment`, added config home dir option.
=> Better environment handling for SDKs, removing almost-duplicate method.

CHANGELOG.md, lib/src/package_analyzer.dart
In the end we haven't used this for analysis on pub.dev, let's remove it.
In the future we may want to have two isolation level for analysis, and it may complicate this method unnecessarily.
=> Remove PackageAnalyzer.inspectVersions()

CHANGELOG.md, bin/pana.dart, lib/src/batch/batch_compare_command.dart, lib/src/batch/batch_run_command.dart, lib/src/sdk_env.dart
- #1320 added config home, but there is still a chance that SDKs sharing the same home config directory would override each other's settings. The new `SdkConfig` ensures that complete separation is possible.
- Also fixing a possible `dartdoc` glitch (not necessarily bug, rather a hard to debug issue) by explicitly calling the `flutter` binary (or its embedded `dart` binary) for Flutter packages. Apparently if `FLUTTER_ROOT` is set, and we are calling an unrelated Dart SDK, `dartdoc` implicitly sets the `--sdk-dir` parameter to `<sdk-root>/bin/cache/dart-sdk/`, which is absent is the regular Dart SDK, and `dartdoc` fails.
=> Support SDK-specific configs (home-path, environment).

CHANGELOG.md, lib/src/package_analyzer.dart, lib/src/package_context.dart
Should address https://github.com/dart-lang/pub-dev/issues/7430
=> Dynamically reduce dartdoc timeout with total time budget option.

test/analysis_options_test.dart, test/license_test.dart, test/markdown_content_test.dart, test/package_server.dart, test/tag/tag_end2end_test.dart, test/tag/tag_external_test.dart, test/tag/tag_null_safe_test.dart
Working towards enabling `package:dart_flutter_team_lints`, this fixes many of the instances of `dynamic` usage introduced within tests, which account for the majority in the package.
=> Start removing `dynamic` usages in tests

lib/src/third_party/diff_match_patch/README.md, lib/src/third_party/diff_match_patch/diff.dart, lib/src/third_party/diff_match_patch/test.dart, lib/src/third_party/diff_match_patch/utils.dart, test/diff_test.dart
Mostly changing a return type of `diffLinesToChars` to a record for static safety and fixing a few variable names.
=> A little cleanup to vendored diff_match_patch

lib/src/report/template.dart, test/goldens/end2end/url_launcher-6.1.12.json, test/goldens/end2end/url_launcher-6.1.12.json_report.md
- https://github.com/dart-lang/pub-dev/issues/7388
- the URL problems are reported, but no point is lost, if the repository is verified
=> Don't reduce points when pubspec URLs are unreachable, but repository is verified.

analysis_options.yaml, lib/src/code_problem.dart, lib/src/license.dart, lib/src/maintenance.dart, lib/src/pkg_resolution.dart, test/ensure_build_test.dart
On the road to switching to `package:dart_flutter_team_lints`.
=> Only use library directives where necessary

lib/src/tag/_specs.dart
This library is used by package:js: https://github.com/dart-lang/sdk/blob/main/pkg/js/lib/js.dart#L8
Otherwise a package using package:js will not be determined web-compatible.
=> Allow import of dart:_js_annotations on web

.github/workflows/publish.yml, .github/workflows/test-package.yml
Closes https://github.com/dart-lang/pana/pull/1293
=> Tighten actions versions and permissions

CHANGELOG.md, README.md, bin/pana.dart, lib/src/sdk_env.dart, lib/src/version.dart, pubspec.yaml, test/goldens/help.txt
=> Fix ambigious dartdoc version value when unspecified.

CHANGELOG.md, lib/src/report/create_report.dart, lib/src/version.dart, pubspec.yaml
This is a follow-up to https://github.com/dart-lang/pub-dev/issues/7430, as it still a pending issue: a large package needs to run `dartdoc` after every other time-consuming analysis (e.g. static analysis or formatted files). Otherwise, e.g. in the case of `package:aws_client` the total timeout is almost exhausted by the time `dartdoc` is being killed because of the dartdoc timeout, and the analysis still needs to run formatting checks.
=> Run 'dartdoc' at a later part of the report.

test/end2end_light_test.dart, test/end2end_test.dart
As a follow-up to #1346, this makes sure that all end2end test start with a fresh temp directory, pub cache and configuration, making sure that one temporary error at one analysis does not hide an issue with a later analysis.
=> Starting each analysis from scratch in end2end tests.

lib/src/dartdoc/dartdoc.dart
https://github.com/dart-lang/pana/issues/1355
=> Suggest using lint for missing API docs

CHANGELOG.md, lib/src/package_analyzer.dart, lib/src/package_context.dart, lib/src/tag/pana_tags.dart, lib/src/version.dart, pubspec.yaml, test/goldens/end2end/steward-0.3.1.json
https://github.com/dart-lang/pub-dev/issues/3780
=> New has:executable tag for dart files in bin/

CHANGELOG.md, lib/src/package_analyzer.dart, lib/src/package_context.dart, lib/src/pubspec.dart, lib/src/report/template.dart, lib/src/version.dart, pubspec.yaml, test/goldens/end2end/gg-1.0.12.json, test/goldens/end2end/onepub-1.1.0.json
- fixes bug with `has:executable` tagging
- verifies the `executables` entry in `pubspec.yaml` and reports it in the layout checks if any of the binary files is missing
=> Verify 'executables' in 'pubspec.yaml' and check if the related files exist

README.md, bin/pana.dart, test/goldens/help.txt
Unless I'm crazy, the help text for `exit-code-threshold` was wrong. I also refactored the relevant code to have the same structure to reduce confusion.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require …
=> Fix exit-code-threshold help text and reorganize code to match

lib/src/model.dart
Reviewed a few pana internals, these are not longer needed by pub-dev.
=> Deprecate a few public API method and field.

CHANGELOG.md, bin/pana.dart, lib/src/logging.dart
The new format is the combination of the current one (which blanks out the prefix on repeated lines) and `pub-dev`'s worker format (which adds a timestamp in the prefix. It also makes the json logging simpler. The code refactor is in the second commit.
This is a less-important, but still required step before the pub worker can invoke the `pana` process without depending on it (while keeping the log format). As the next step, while the `pub_worker` still depends on `pana` as a library, it may use the separate method to initialize the logging.
=> New text logging format + moving initialization to new method

CHANGELOG.md, bin/pana.dart, lib/src/package_analyzer.dart, lib/src/package_context.dart, lib/src/sdk_env.dart, test/end2end_test.dart
- Removing the `panaCache` field from `ToolEnvironment` is breaking change, but I don't expect anybody using it, esp. because (a) it was not documented and (b) the `PanaCache` class is not exposed in the API.
- `InspectOptions` is a better place for specifying its value (if there is any shared cache between analysis sessions).
Note: `SharedAnalysisContext` is not a public API, we may use it there without any issues.
=> Move PanaCache out of ToolEnvironment (also from public API), adding in InspectOptions

CHANGELOG.md, lib/src/model.dart, lib/src/model.g.dart, lib/src/package_analyzer.dart, pubspec.yaml, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json, test/goldens/end2end/async-2.11.0.json, test/goldens/end2end/audio_service-0.18.10.json, test/goldens/end2end/bulma_min-0.7.4.json, test/goldens/end2end/dnd-2.0.1.json, test/goldens/end2end/gg-1.0.12.json, test/goldens/end2end/http-0.13.0.json, test/goldens/end2end/lints-1.0.0.json, test/goldens/end2end/mime_type-0.3.2.json, test/goldens/end2end/nsd_android-1.2.2.json, test/goldens/end2end/onepub-1.1.0.json, test/goldens/end2end/sdp_transform-0.2.0.json, test/goldens/end2end/skiplist-0.1.0.json, test/goldens/end2end/steward-0.3.1.json, test/goldens/end2end/url_launcher-6.1.12.json, test/goldens/end2end/webdriver-3.0.0.json
- Deprecated classes and fields that will become obsolete.
- Added new `licenses` field to `AnalysisResult`.
- The change is an overdue migration that also cleans up a half-migration of `LicenseFile`.
- I've considered to use another class name instead of reusing `License`, but the name seems to be fit, and its migration would be too complicated. We just won't need to remove the `path` field, and we may add confidence classification or score later to it. (An upcoming breaking change should clean up these loose threads.)
=> Migrating Summary.licenseFile and Summary.licenses to AnalysisResult.licenses

CHANGELOG.md, lib/src/report/_common.dart
https://github.com/dart-lang/pub-dev/pull/7871
=> Mark renderSimpleSectionSummary as deprecated.

analysis_options.yaml, lib/src/batch/batch_compare_command.dart, lib/src/batch/batch_query_command.dart, lib/src/batch/batch_run_command.dart, lib/src/license.dart, lib/src/license_detection/license_detector.dart, lib/src/package_analyzer.dart, lib/src/report/static_analysis.dart, lib/src/report/template.dart, lib/src/repository/check_repository.dart, lib/src/screenshots.dart, lib/src/third_party/diff_match_patch/diff.dart, lib/src/third_party/diff_match_patch/test.dart, lib/src/tool/git_tool.dart, lib/src/tool/run_constrained.dart, pubspec.yaml, test/license_detector_test.dart, test/pubspec_test.dart
Manually disabling some lints for now, as they throw many errors.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testi …
=> Switch to `package:dart_flutter_team_lints`

CHANGELOG.md, lib/src/sdk_env.dart, lib/src/version.dart, pubspec.yaml
Fixes https://github.com/dart-lang/pana/issues/1369
=> Remove workspace and resolution from pubspec.yaml before resolving

CHANGELOG.md, lib/src/package_analyzer.dart
Needed for https://github.com/dart-lang/pub-dev/pull/8173
=> Ignore git error on repository root detection.

lib/src/dartdoc/dartdoc_internals.dart, test/dartdoc/dartdoc_internals_test.dart
This is assuming that the new href URLs in dartdoc will get an ending slash: https://github.com/dart-lang/dartdoc/issues/3936
=> Detect library hrefs with or without ending slash.

CHANGELOG.md, lib/src/internal_model.dart, lib/src/internal_model.g.dart, lib/src/model.dart, lib/src/model.g.dart, lib/src/package_analyzer.dart, lib/src/package_context.dart, lib/src/references/pubspec_urls.dart, lib/src/report/template.dart, lib/src/repository/check_repository.dart, test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json, test/goldens/end2end/async-2.11.0.json, test/goldens/end2end/audio_service-0.18.15.json, test/goldens/end2end/bulma_min-0.7.4.json, test/goldens/end2end/dnd-2.0.1.json, test/goldens/end2end/gg-1.0.12.json, test/goldens/end2end/http-0.13.0.json, test/goldens/end2end/lints-1.0.0.json, test/goldens/end2end/lints-1.0.0.json_report.md, test/goldens/end2end/mime_type-0.3.2.json, test/goldens/end2end/nsd_android-2.1.2.json, test/goldens/end2end/onepub-1.1.0.json, test/goldens/end2end/sdp_transform-0.2.0.json, test/goldens/end2end/skiplist-0.1.0.json, test/goldens/end2end/steward-0.3.1.json, test/goldens/end2end/url_launcher-6.3.1.json, test/goldens/end2end/webdriver-3.0.0.json
- #1403
- I think we may have a path to introduce stricter checks without breaking the pana output much, this is a first step to it.
- Note: this follows the previous concept of keeping the `AnalysisResult` object compact, while exposing any issue or failure message in the report.
=> Expose more precise repository verification status in 'AnalysisResult'.

CHANGELOG.md, lib/src/package_analyzer.dart, lib/src/references/pubspec_urls.dart, lib/src/report/template.dart, test/goldens/end2end/url_launcher-6.3.1.json
- #1403
- Instead of relying on the issue message string, store an explicit status whether the URL could be displayed or not. (non-secure URLs will not be displayed, but ones with 404 will be).
- The accepted URLs are also exposed in the `AnalysisResult`.
=> Use explicit URL issue status and display the accepted ones in the results.

CHANGELOG.md, lib/src/license_detection/license_detector.dart, lib/src/license_detection/token_matcher.dart, test/license_detector_test.dart, test/licenses/license_coverage_test.dart
- Fixes #1484.
- The `findLongestUnclaimedTokenRange` is used to filter out detection results where the unclaimed/unrecognized range is too long (50+ tokens), however, with trailing contained ranges the calculation is wrong.
- Related to #1488, as the contained range is a smaller version of the license. In such cases we should also remove the smaller version, but in that case the edge case bug here wouldn't be noticeable.
=> Fixing license match post-filtering calculation with traling contained range.

lib/src/license_detection/license_detector.dart, test/license_detector_test.dart, test/licenses/license_coverage_test.dart
=> Fix bug in removeOverLappingMatches

lib/src/license.dart, lib/src/license_detection/lcs.dart
- #1487
- group tokens under operations
- backtracking the distance table no longer requires repeating the string comparison
=> Calculate token-based edit operations.
