dart-lang/pana

lib/src/scoring.dart
test/end2end/pub_server_data.dart
test/end2end_test.dart
test/scoring_test.dart

Add scoring logic inspired by npms.io work

---

test/end2end/pub_server_data.dart
test/end2end_test.dart

Let’s us embed matchers – should be easier to handle small changes to output

Use dart files to store the expected output

---

lib/src/platform.dart
lib/src/pubspec.dart
test/platform_test.dart
test/pubspec_test.dart

I've deferred to make it part of the summary, in case you decide that we shall merge the library-level analysis.

Platform detection basics.

---

lib/src/platform.dart
lib/src/summary.dart
test/end2end_test.dart

Validate that Platform JSON round-trips cleanly

---

lib/pana.dart
lib/src/mini_sum.dart
lib/src/pub_summary.dart
lib/src/summary.dart
test/pub_summary_test.dart

Use the new issue logic infrastructure
Don't run analysis over packages without successful `pub-upgrade`
...too much noise with missing imports
Closes https://github.com/dart-lang/pana/issues/18

Remove all error logic handling from PubSummary

---

analysis_options.yaml
lib/src/analyzer_output.dart
lib/src/analyzer_output.g.dart
lib/src/platform.dart
lib/src/platform.g.dart
lib/src/pub_summary.dart
pubspec.yaml
tool/README.md
tool/build.dart
tool/phases.dart
tool/watch.dart

Use source_gen for JSON serialization

---

.travis.yml
analysis_options.yaml
bin/main.dart
lib/pana.dart
lib/src/library_analyzer.dart
lib/src/license.dart
lib/src/platform.dart
lib/src/pubspec.dart
lib/src/summary.dart
lib/src/utils.dart
test/platform_test.dart

Builds off https://github.com/dart-lang/pana/pull/42

Graph and refactor

---

lib/src/sdk_env.dart

Fixes https://github.com/dart-lang/pana/issues/49

Only log pub upgrade at io verbosity

---

lib/pana.dart
lib/src/fitness.dart
lib/src/fitness.g.dart
lib/src/summary.dart
lib/src/summary.g.dart
test/end2end/http_data.dart
test/end2end/pub_server_data.dart
tool/build_actions.dart

As usual, naming is hard. `Fitness` is a lightweight version of `health`, with the major difference that `health` would get a deeper analysis, for example:
- running code (e.g. tests)
- code coverage
- readability
It is proportional to the library size (see https://github.com/dart-lang/pub-dartlang-dart/issues/305).

Calculate file and package fitness

---

CHANGELOG.md
lib/pana.dart
lib/src/mini_sum.dart
lib/src/pub_summary.dart
lib/src/pub_summary.g.dart
lib/src/summary.dart
lib/src/summary.g.dart
test/end2end/http_data.dart
test/end2end/pub_server_data.dart
test/pub_summary_test.dart

This PR has a lot of functional change, I've tried my best to match the old behavior, but there are obvious differences (e.g. to store the dependency type and the constraint type).

Refactor PubSummary to PkgResolution

---

CHANGELOG.md
bin/summarize.dart
lib/pana.dart
lib/src/fitness.dart
lib/src/platform.dart
lib/src/platform.g.dart
lib/src/summary.dart
lib/src/summary.g.dart
test/end2end/http_data.dart
test/end2end/pub_server_data.dart
test/end2end/shared.dart
test/end2end_test.dart
test/platform_test.dart

Apologies, the change got a bit large, and I had to tweak the platform classification a bit, but I hope the end result got simpler.

Refactor platform, using a single DartPlatform class

---

lib/src/license.dart
test/license_test.dart
test/licenses/agpl_v3.txt
test/licenses/apache_v2.txt
test/licenses/bsd_2_clause.txt
test/licenses/bsd_3_clause.txt
test/licenses/bsd_revised.txt
test/licenses/gpl_v3.txt
test/licenses/lgpl_v3.txt
test/licenses/mit.txt
test/licenses/mpl_v2.txt
test/licenses/unlicense.txt

(Not the multi-license detection yet, seems to be trickier in case of GPL, MPL, LGPL and AGPL, which reference each other by name in their body.)

More license test and small fixes.

---

CHANGELOG.md
lib/pana.dart
lib/src/license.dart
lib/src/summary.dart
lib/src/summary.g.dart
lib/src/version.g.dart
pubspec.yaml
test/end2end/http_data.dart
test/end2end/pub_server_data.dart
test/license_test.dart

(Detection change will be part of a subsequent PR.)

Return multiple licenses.

---

lib/src/platform.dart

If there is a primary library and it works everywhere – go with that
Addresses https://github.com/dart-lang/pub-dartlang-dart/issues/455

Fix platform classification for primary library

---

lib/src/sdk_env.dart
lib/src/utils.dart

Increase timeout and make sure all async process calls use it.

---

lib/src/fitness.dart

Calculate health score from Fitness.

---

CHANGELOG.md
bin/main.dart
lib/pana.dart
lib/src/sdk_env.dart
lib/src/sdk_info.dart
lib/src/summary.dart
lib/src/summary.g.dart
lib/src/version.g.dart
pubspec.yaml
test/end2end/http_data.dart
test/end2end/pub_server_data.dart
test/end2end/shared.dart
test/end2end/skiplist_data.dart
test/end2end_test.dart

Fixes https://github.com/dart-lang/pana/issues/135

`Summary.sdkVersion` is now a `Version` instead of `String`

---

lib/src/summary.dart
lib/src/summary.g.dart

Makes scanning the raw file easier

Summary: move pkgResolution and dartFiles to end of serialized output

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/summary.dart
lib/src/version.g.dart
pubspec.yaml

Closes https://github.com/dart-lang/pana/issues/143

Categorize suggestions as bugs if they represent tool failures

---

CHANGELOG.md
lib/src/code_problem.dart

Unblock platform classification on a new class of errors.

---

lib/src/code_problem.dart

Closes https://github.com/dart-lang/pana/issues/165

Also allow code ARGUMENT_TYPE_NOT_ASSIGNABLE to not block classification

---

CHANGELOG.md
lib/src/maintenance.dart
lib/src/summary.dart
pubspec.yaml
test/maintenance_test.dart

Allows testing
Also added tests for Maintenance

Maintenance: add optional `now` positional param to getMaintenanceScore

---

CHANGELOG.md
lib/src/maintenance.dart
lib/src/maintenance.g.dart
lib/src/summary.dart
lib/src/summary.g.dart
test/end2end/http_data.dart
test/end2end/pub_server_data.dart
test/end2end/skiplist_data.dart
test/maintenance_test.dart

An alternative take on how to explain maintenance score values.
- I've kept the commits short to keep a narrative easier to follow.
- I've reduced the penalties for 0.* versions and beta releases.
- I've reduced the penalties for cumulative errors/warning/hints.

Maintenance explainations

---

test/end2end/stream_broken_data.dart

Got broken by two parallel changes.

Fix test and CI

---

lib/src/license.dart
test/license_test.dart
test/licenses/bad_encoding.txt

Closes #181 (up for debate, but I think this is the best effort we can do).

Don't fail hard on bad license file encoding.

---

lib/src/package_analyzer.dart

Block platform classification only on reachable libraries.

---

CHANGELOG.md
lib/src/fitness.dart
lib/src/package_analyzer.dart
lib/src/pubspec.dart
lib/src/version.g.dart
pubspec.yaml
test/end2end/stream_broken_data.dart
test/pubspec_test.dart

Only direct unconstrained dependencies decrease the health score.

---

README.md
bin/pana.dart
lib/src/package_analyzer.dart
lib/src/sdk_env.dart
test/bin_pana_test.dart

- Creates backup of `pubspec.yaml` and restores it.
- Fixes #204

Enable local project analysis through command-line.

---

CHANGELOG.md
lib/src/maintenance.dart
lib/src/package_analyzer.dart
lib/src/pubspec.dart
test/end2end/http_data.dart
test/end2end/skiplist_data.dart
test/maintenance_test.dart

I've expanded the range, because people tend to follow these numbers too closely, and I think a bit of buffer zone eases the pressure there. Fixes #201.

Recommend descriptions between 60 and 180 characters.

---

lib/src/download_utils.dart
lib/src/license.dart
test/download_utils_test.dart

This will be reused in pub site too.

Better handling of repository-relative URLs.

---

CHANGELOG.md
lib/src/fitness.dart
lib/src/maintenance.dart
lib/src/package_analyzer.dart
lib/src/pkg_resolution.dart
test/maintenance_test.dart

Move unconstrained version penalty from health score to maintenance.

---

CHANGELOG.md
lib/src/fitness.dart
lib/src/maintenance.dart
lib/src/package_analyzer.dart
test/end2end/stream_broken_data.dart
test/maintenance_test.dart

Move platform conflict penalty from health score to maintenance

---

CHANGELOG.md
lib/src/maintenance.dart
lib/src/summary.dart
test/end2end/http_data.dart
test/end2end/pub_server_data.dart
test/end2end/skiplist_data.dart
test/end2end/stream_broken_data.dart
test/maintenance_test.dart

It also uses the penalty for the same-level suggestions.

Sort maintenance suggestions in decreasing importance.

---

CHANGELOG.md
lib/src/pkg_resolution.dart

Do not report on unconstrained SDK dependencies.

---

CHANGELOG.md
lib/src/sdk_env.dart

Remove dependency_overrides from pubspec for analysis.

---

CHANGELOG.md
lib/src/version.g.dart
pubspec.yaml

It looks like many tool failures are handled with with the 0.20 SDK and some of the recent changes, let's do a release!

Preparing 0.10.1 release

---

CHANGELOG.md
pubspec.yaml

Update analyzer to 0.31 and extends quiver version range.

---

CHANGELOG.md
lib/src/sdk_env.dart

Fix issue where we were not passing the proper package directory variable.

---

CHANGELOG.md
lib/src/code_problem.dart
lib/src/fitness.dart
lib/src/fitness.g.dart
lib/src/maintenance.dart
lib/src/package_analyzer.dart
lib/src/summary.dart
test/end2end/http_data.dart
test/end2end/pub_server_data.dart
test/end2end/skiplist_data.dart
test/end2end/stream_broken_data.dart
test/maintenance_test.dart

This ended up a bit longer than expected, but it closes #222 and also closes https://github.com/dart-lang/pub-dartlang-dart/issues/692. Increases the fine-grained data in the output, but the rendered parts on the pub site will be compact.

Expose all dartanalyzer and dartfmt problems as suggestions.

---

CHANGELOG.md
lib/src/version.g.dart
pubspec.yaml
test/ensure_build_test.dart

Fix CI test.

---

.travis.yml
CHANGELOG.md
analysis_options.yaml
lib/src/analysis_options.dart
lib/src/version.g.dart
pubspec.yaml
test/analysis_options_test.dart

I'm not sure which SDK started to support it, I've bumped the CI to the latest as part of this change.
https://github.com/dart-lang/pub-dartlang-dart/issues/1120

Use enablePreviewDart2 in Flutter analysis options.

---

CHANGELOG.md
lib/src/platform.dart
test/end2end/pub_server_data.dart
test/platform_test.dart

Change platform classification of dart:isolate: no longer available on web

---

.travis.yml

At first it looked like there are some changes in the test output, but a clean setup showed it is a straightforward upgrade.

Bump CI version to dev-44.

---

CHANGELOG.md
lib/src/library_scanner.dart

https://github.com/dart-lang/pub-dartlang-dart/issues/1170

Use LibraryElement.hasExtUri to detect dart-ext: imports.

---

CHANGELOG.md
lib/src/fitness.dart
lib/src/maintenance.dart
lib/src/package_analyzer.dart
test/end2end/stream_broken_data.dart
test/maintenance_test.dart

Detailed suggestion messages when package has conflicting platforms.

---

CHANGELOG.md
lib/src/version.g.dart
pubspec.yaml

After the two current pending PR get merged.

0.10.6 release

---

CHANGELOG.md
bin/pana.dart
lib/src/package_analyzer.dart
test/end2end_test.dart

Adding further ones in a later PRs.

Consolidating options in InspectOptions, changing PackageAnalyzer APIs.

---

CHANGELOG.md
lib/src/download_utils.dart
lib/src/maintenance.dart
lib/src/pubspec.dart
test/maintenance_test.dart

Check homepage and documentation properties to point to an existing and external web page.

---

CHANGELOG.md
README.md
bin/pana.dart
lib/src/model.dart
lib/src/model.g.dart
lib/src/package_analyzer.dart
test/bin_pana_test.dart
test/end2end/stream_broken_data.dart
test/end2end_test.dart

--verbose command-line and Verbosity option to control the details in the output.

---

lib/src/sdk_env.dart

https://github.com/dart-lang/pub-dartlang-dart/issues/1254

Support dartdoc's --link-to-remote

---

CHANGELOG.md
lib/src/version.g.dart
pubspec.yaml

After the pending PR gets merged, I think it will be a good time to make a release and retrofit the pub site with all these breaking changes.

Prepare 0.11.0 release.

---

CHANGELOG.md
lib/src/sdk_env.dart
lib/src/version.g.dart
pubspec.yaml

0.19 handles it:
https://github.com/dart-lang/pub-dartlang-dart/issues/1254

Do not excluded libs in dartdoc processing.

---

lib/pana.dart
lib/src/dartdoc_analyzer.dart
lib/src/maintenance.dart

First refactoring step towards a separate analysis path for `dartdoc` (https://github.com/dart-lang/pub-dartlang-dart/issues/992)

Move dartdoc-related suggestion to a separate file.

---

CHANGELOG.md
lib/src/maintenance.dart
test/maintenance_test.dart

We have used it for the score calculation, but never displayed it. Added some tests too.

expose getAgeSuggestion method for pub site

---

lib/src/model.g.dart

Similar to the pub site, a dependency upgrade requires re-running.

Fix build: re-running codegen

---

CHANGELOG.md
lib/src/version.g.dart
pubspec.yaml

Prepare 0.11.3 release

---

analysis_options.yaml
bin/pana.dart
lib/src/analysis_options.dart
lib/src/license.dart
lib/src/logging.dart
lib/src/model.dart
lib/src/model.g.dart
lib/src/package_analyzer.dart
lib/src/pkg_resolution.dart
lib/src/pubspec.dart
lib/src/sdk_env.dart
lib/src/utils.dart
test/end2end_test.dart
tool/src/version_helper.dart

Going ahead of these changes...

Disable implicit casts

---

lib/src/pkg_resolution.dart
lib/src/pubspec.dart
pubspec.yaml
test/pub_summary_test.dart
test/pubspec_test.dart

Local Pubspec class is now a thin wrapper over the pkg class

Use new pubspec_parse package

---

.travis.yml
test/end2end/http-0.11.3-13.json
test/end2end/pub_server-0.1.1-3.json
test/end2end/skiplist-0.1.0.json
test/end2end/stream-0.7.2-2.json

Also included end2end test updates, because their failure triggered the CI upgrade.

 Upgrade CI to dev.62 SDK

---

lib/src/messages.dart
lib/src/platform.dart
test/messages_test.dart

I've settled with displaying either three items in full, or two + "and X more" where is always X>=2.

Compact sample building for platform conflict description.

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/utils.dart
lib/src/version.g.dart
pubspec.yaml

To address https://github.com/dart-lang/pub-dartlang-dart/issues/1347

Less verbose logging.

---

lib/src/maintenance.dart
lib/src/model.dart
pubspec.yaml
test/end2end/fs_shim-0.7.1.json
test/end2end/http-0.11.3-13.json
test/end2end/pub_server-0.1.1-3.json
test/end2end/skiplist-0.1.0.json
test/end2end/stream-0.7.2-2.json
test/end2end_test.dart
test/maintenance_test.dart

The `fs_shim` test was failing with the previous version of `pubspec_parse`, added it for an early warning.

Upgrade pubspec_parse and adding end2end test.

---

CHANGELOG.md
lib/src/maintenance.dart
test/end2end/fs_shim-0.7.1.json
test/end2end/http-0.11.3-13.json
test/end2end/pub_server-0.1.1-3.json
test/end2end/skiplist-0.1.0.json
test/end2end/stream-0.7.2-2.json
test/maintenance_test.dart

Fixes #360.
I've eventually opted for "Fix additional 12 files with analysis or formatting issues.", as it makes it clear that it is about 12 files and not 12 issues.

Update suggestion messages.

---

CHANGELOG.md
lib/src/version.g.dart
pubspec.yaml

I think the important changes are already merged for a new release.

Preparing 0.11.5 release

---

CHANGELOG.md
build.yaml
lib/src/version.g.dart
pubspec.yaml

And other dev_dependency updates

Support Dart 2 gold release

---

CHANGELOG.md
lib/src/maintenance.dart
test/end2end/dartdoc-0.20.0.json
test/end2end/fs_shim-0.7.1.json
test/end2end/http-0.11.3-13.json
test/end2end/pub_server-0.1.1-3.json
test/end2end/skiplist-0.1.0.json
test/end2end/stream-0.7.2-2.json
test/maintenance_test.dart

https://github.com/dart-lang/pub-dartlang-dart/issues/1482

Remove strong-mode: true check and suggestion

---

CHANGELOG.md
lib/src/download_utils.dart
lib/src/license.dart
lib/src/maintenance.dart
lib/src/package_analyzer.dart
test/maintenance_test.dart

https://github.com/dart-lang/pub-dartlang-dart/issues/1389

Do not check existence of non-external URLs.

---

CHANGELOG.md
lib/src/version.g.dart
pubspec.yaml

Let's do a new release after the current PRs got merged.

Prepare new release: 0.11.8

---

CHANGELOG.md
bin/pana.dart

Closes https://github.com/dart-lang/pana/issues/390

Support relative local path with --source path

---

lib/src/package_analyzer.dart

Closes all known items in https://github.com/dart-lang/pana/issues/368

Parse errors and don't log tool errors on user problems.

---

lib/src/download_utils.dart
lib/src/maintenance.dart
lib/src/package_analyzer.dart
test/maintenance_test.dart

https://github.com/dart-lang/pana/issues/386
Alternative to https://github.com/dart-lang/pana/pull/393

Flag for internal packages and handle warnings differently.

---

README.md
bin/pana.dart
test/bin_pana_test.dart

https://github.com/dart-lang/pana/issues/390

Update CLI help message.

---

bin/pana.dart

Closes https://github.com/dart-lang/pana/issues/391

Omit stack trace for known user input errors.

---

CHANGELOG.md
lib/src/health.dart
lib/src/model.dart
lib/src/model.g.dart
lib/src/package_analyzer.dart
test/end2end/dartdoc-0.20.0.json
test/end2end/fs_shim-0.7.1.json
test/end2end/http-0.11.3-13.json
test/end2end/pub_server-0.1.1-3.json
test/end2end/skiplist-0.1.0.json
test/end2end/stream-0.7.2-2.json

Closes https://github.com/dart-lang/pana/issues/369

Track tool failures and set health score to 0 if there is any.

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

I don't have anything urgent to put into the next release, let's release this and fix it in pub site.

Prepare 0.12.2 release

---

CHANGELOG.md
lib/src/sdk_env.dart
lib/src/version.dart
pubspec.yaml

https://github.com/dart-lang/pub-dartlang-dart/issues/1605

Increased dartfmt timeout to 5 minutes.

---

CHANGELOG.md
lib/src/maintenance.dart

https://github.com/dart-lang/pana/issues/408

Detect example/readme.md (or similar pattern) as an alternative to single .dart example.

---

README.md
lib/src/maintenance.dart
lib/src/model.dart

/cc @mit-mit 
preview url: https://github.com/dart-lang/pana/blob/77291ab6b30d6c604aeef2c3f0a7786b8ac56f00/README.md

Document scoring rules in README

---

README.md

Fix documentation for missing SDK constraint.

---

build.yaml
lib/src/version.dart
pubspec.yaml

analyzer
http
build
build_runner
build_version

Update supported versions of a number of dependencies

---

lib/src/sdk_env.dart

#418
@shamblett is there any chance that you can try this branch on your windows setup?

Use .exe and .bat extensions on Windows.

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

Prepare 0.12.6 release

---

test/end2end/dartdoc-0.24.1.json
test/end2end/stream-2.0.1.json

A new release in `rikulo_commons` added an extra error in `stream` analysis.

Fix end2end test.

---

CHANGELOG.md
README.md
lib/src/maintenance.dart
lib/src/pubspec.dart
test/end2end/dartdoc-0.24.1.json
test/end2end/fs_shim-0.7.1.json
test/end2end/skiplist-0.1.0.json

Display Dart SDK warning if package doesn't allow the latest Dart 2.X version.

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

Let's do a release after #449 gets merged.

Prepare release: 0.12.7

---

CHANGELOG.md
lib/src/license.dart
lib/src/version.dart
pubspec.yaml
test/end2end/dartdoc-0.24.1.json
test/end2end/fs_shim-0.7.1.json
test/end2end/skiplist-0.1.0.json
test/end2end_test.dart

- follow-up on obsolete TODOs
- updated end2end tests again, as their dependencies changed their files

Code cleanup

---

CHANGELOG.md
lib/src/model.dart
lib/src/package_analyzer.dart
test/end2end/syntax-0.2.0.json
test/end2end_test.dart

Handle package with bad pubspec.yaml.

---

CHANGELOG.md
lib/src/analysis_options.dart
pubspec.yaml
test/analysis_options_test.dart

* removes stale analyzer options
* resyncs w/ flutter user options
/cc @isoos @kevmoo

update analysis options

---

CHANGELOG.md
README.md
bin/pana.dart
lib/src/package_analyzer.dart
lib/src/sdk_env.dart
lib/src/version.dart
pubspec.yaml
test/bin_pana_test.dart
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/http-0.11.3-17.json
test/end2end/pub_server-0.1.4-2.json
test/end2end/stream-2.0.1.json

pub site won't use it, but it seems to be useful for local tests: #468

Support --line-length option.

---

lib/src/version.dart
pubspec.yaml

I think the parsing fix makes it worth to release it now, I'd like to see it on pub site.

Prepare 0.12.10 release.

---

CHANGELOG.md
README.md
lib/src/maintenance.dart
lib/src/model.dart
lib/src/pubspec.dart

I've done a bit of fiddling with the error message, but eventually settled with this short one.
Fixes #475.

Maintenance score penalty for using git dependencies.

---

lib/src/package_analyzer.dart

Suppress more log when the pub upgrade error could be git-related.

---

test/end2end/fs_shim-0.7.1.json
test/end2end/skiplist-0.1.0.json
test/end2end_test.dart

Mask current SDK version in golden files.

---

CHANGELOG.md
lib/src/maintenance.dart
lib/src/version.dart
pubspec.yaml
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/fs_shim-0.7.1.json
test/end2end/http-0.11.3-17.json
test/end2end/skiplist-0.1.0.json
test/end2end/stream-2.0.1.json
test/maintenance_test.dart

https://github.com/dart-lang/pub-dartlang-dart/issues/1973

Link to package layout conventions in example-related suggestions.

---

lib/src/sdk_env.dart

Remove stacktrace from Flutter version failures.

---

CHANGELOG.md
lib/src/maintenance.dart
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/http-0.11.3-17.json
test/end2end/pub_server-0.1.4-2.json
test/end2end/stream-2.0.1.json

I've found it annoying to have 58-character long description with full penalty.

Linear penalties for description.

---

lib/src/maintenance.dart

https://github.com/dart-lang/pub-dartlang-dart/issues/1960

Formatted CheckedFromJsonException

---

lib/src/maintenance.dart

Fine-tune checked json exception message.

---

CHANGELOG.md
README.md
bin/pana.dart
test/bin_pana_test.dart
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/stream-2.0.1.json

I wanted to enable #503, but didn't wanted to include the scores in the output model by default, as we are adding additional items on top of it.

Display calculated health and maintenance scores.

---

CHANGELOG.md
lib/src/maintenance.dart
test/end2end_test.dart
test/maintenance_test.dart

Ask for example only for packages with public libraries.

---

CHANGELOG.md
lib/src/sdk_env.dart
lib/src/version.dart
pubspec.yaml
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/http-0.11.3-17.json
test/end2end/pub_server-0.1.4-2.json
test/end2end/stream-2.0.1.json

Fix: delete local temporary pedantic_analyis_options_[timestamp].g.yaml.

---

test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/http-0.11.3-17.json
test/end2end/pub_server-0.1.4-2.json
test/end2end/stream-2.0.1.json

`package:stream_channel` removed its direct dependency on isolate (got a separate library).

Update end2end tests.

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/stream-2.0.1.json

Most of the end2end changes comes from upgraded `pedantic` rules (we don't control the version of it).

Upgrade analyzer and prepare release.

---

lib/src/version.dart
pubspec.yaml

I've realized that to upgrade the version of pedantic on the pub site, we also need to release this with the fix. please merge this and publish the new version of pana.

Prepare release

---

README.md
lib/src/package_analyzer.dart

Related to flutter/flutter#33041

Change `flutter packages` to `flutter pub`

---

CHANGELOG.md
lib/src/license.dart
lib/src/maintenance.dart
lib/src/utils.dart
lib/src/version.dart
pubspec.yaml
test/license_test.dart

Following the specification in https://github.com/dart-lang/site-www/pull/1640

Recognize more file patterns.

---

test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/pub_server-0.1.4-2.json
test/end2end/stream-2.0.1.json

Updated end2end tests.

---

CHANGELOG.md
lib/src/maintenance.dart
lib/src/version.dart
pubspec.yaml
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/fs_shim-0.7.1.json
test/end2end/skiplist-0.1.0.json
test/maintenance_test.dart

Updated suggestion for not supporting future stable SDKs.

---

CHANGELOG.md
lib/src/model.g.dart
pubspec.yaml

Support the latest pkg:json_annotation

---

CHANGELOG.md
lib/src/maintenance.dart
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/http-0.11.3-17.json
test/end2end/pub_server-0.1.4-2.json
test/end2end/stream-2.0.1.json

Apply dependency constraint penalty only if the pubspec constraint is responsible for it.

---

test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/fs_shim-0.7.1.json
test/end2end/http-0.11.3-17.json
test/end2end/pub_server-0.1.4-2.json
test/end2end/skiplist-0.1.0.json
test/end2end/stream-2.0.1.json

- some of it is only diffferent JSON key order
- the breaking parts were: new dependencies and different analysis errors

Fix end2end tests on CI

---

CHANGELOG.md
lib/src/download_utils.dart
lib/src/version.dart
pubspec.yaml

https://github.com/dart-lang/pub-dev/issues/3039

Follow redirects in UrlChecker

---

lib/src/version.dart
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/fs_shim-0.7.1.json
test/end2end/http-0.11.3-17.json
test/end2end/pub_server-0.1.4-2.json
test/end2end/skiplist-0.1.0.json
test/end2end/stream-2.0.1.json

Follow-up to: https://github.com/dart-lang/pana/pull/574

Update golden filed

---

CHANGELOG.md
README.md
lib/src/health.dart
lib/src/maintenance.dart
lib/src/model.dart
lib/src/package_analyzer.dart
lib/src/version.dart
pubspec.yaml
test/end2end/fs_shim-0.7.1.json
test/end2end/skiplist-0.1.0.json
test/maintenance_test.dart

https://github.com/dart-lang/pana/issues/587

Don't penalize packages on legacy platform detection results.

---

lib/src/download_utils.dart
pubspec.yaml

Use package:safe_url_check

---

CHANGELOG.md
README.md
lib/src/model.dart
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json
test/end2end/stream-2.0.1.json

Limit overall style lint penalties on health score: 25%.

---

CHANGELOG.md
lib/src/maintenance.dart
test/end2end/angular_components-0.10.0.json
test/end2end/dartdoc-0.24.1.json

https://github.com/dart-lang/pub-dev/issues/3298

De-prioritize readme in example detection.

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/version.dart
pubspec.yaml

Detect Dart files on Windows

---

lib/src/package_analyzer.dart
test/end2end/angular_components-0.10.0.json
test/end2end/stream-2.0.1.json

Alternative fix for https://github.com/dart-lang/pub-dev/issues/3430

Don't do tag-detection when errors are detected

---

lib/src/tag_detection.dart
test/tag_detection_test.dart

Fixes https://github.com/dart-lang/pub-dev/issues/3430

Ignore file: imports when analyzing tags

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/version.dart
pubspec.yaml

Reported in https://github.com/dart-lang/pub-dev/issues/3457

Fix: NPE after dartanalyzer exits with a failure.

---

bin/pana.dart

And use '.' for the default path.
This will smoothen the workflow of checking a local package - probably
the most common.

Use --source=path by default

---

lib/src/tag_detection.dart
test/tag_detection_test.dart

Fixes: https://github.com/dart-lang/pana/issues/639

Add tag-detection for old-style flutter plugins

---

lib/src/tag_detection.dart
test/tag_detection_test.dart

Fixes: https://github.com/dart-lang/pana/issues/675

Handle broken imports and dependencies from tagging

---

lib/src/create_report.dart

Fixes: https://github.com/dart-lang/pana/issues/674

Fix NPE when there is no flutter sdk constraint

---

lib/src/create_report.dart

Fixes https://github.com/dart-lang/pana/issues/713

Ignore issues with CR as line terminators

---

lib/src/utils.dart

Fix of https://github.com/dart-lang/pana/issues/684

Avoid crashing on overly long stderr from subprocess

---

lib/src/sdk_env.dart

Fixes https://github.com/dart-lang/pana/issues/721

Handle new `dart --version output`

---

CHANGELOG.md
lib/src/markdown_content.dart
test/goldens/end2end/dartdoc-0.24.1.json
test/goldens/end2end/dartdoc-0.24.1.json_report.md
test/markdown_content/bad_images.md
test/markdown_content/example.md
test/markdown_content_test.dart

Fix: mailto links are no longer classified as unsecure.

---

CHANGELOG.md
lib/src/download_utils.dart
test/download_utils_test.dart

Fixes https://github.com/dart-lang/pub-dev/issues/3856

Download URLs recognize .git when linking to a file.

---

lib/src/create_report.dart
lib/src/package_analyzer.dart
lib/src/pubspec.dart
lib/src/pubspec_io.dart
lib/src/sdk_env.dart
lib/src/tag_detection.dart

Allows importing of this code via web
Needed for tools

Move dart:io code from Pubspec

---

pubspec.yaml

Reintroduce dependency on package:io

---

test/pub_summary_test.dart

Doesn't affect anything
Will avoid a false positive in searches for these terms

Remove unneeded reference to slave in test input file

---

CHANGELOG.md
lib/src/create_report.dart
lib/src/version.dart
pubspec.yaml
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.0.json
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.0.json_report.md
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json_report.md
test/goldens/end2end/angular_components-0.10.0.json
test/goldens/end2end/angular_components-0.10.0.json_report.md
test/goldens/end2end/bulma_min-0.7.4.json
test/goldens/end2end/bulma_min-0.7.4.json_report.md
test/goldens/end2end/fs_shim-0.7.1.json
test/goldens/end2end/fs_shim-0.7.1.json_report.md
test/goldens/end2end/http-0.11.3+17.json
test/goldens/end2end/http-0.11.3+17.json_report.md
test/goldens/end2end/mime_type-0.3.2.json
test/goldens/end2end/mime_type-0.3.2.json_report.md
test/goldens/end2end/pub_server-0.1.4+2.json
test/goldens/end2end/pub_server-0.1.4+2.json_report.md
test/goldens/end2end/skiplist-0.1.0.json
test/goldens/end2end/skiplist-0.1.0.json_report.md
test/goldens/end2end/stream-2.0.1.json
test/goldens/end2end/stream-2.0.1.json_report.md

Also contains a few other small improvements

Clarify why null safety section gives zero points

---

lib/src/utils.dart

To help debugging issues like https://github.com/dart-lang/pub-dev/issues/4261

Adjust runProc timeout/kill handler.

---

lib/src/dartdoc_analyzer.dart

https://github.com/dart-lang/pub-dev/issues/4261

Better timeout message for dartdoc section.

---

CHANGELOG.md
lib/src/sdk_env.dart
test/end2end_test.dart
test/goldens/end2end/sdp_transform-0.2.0.json
test/goldens/end2end/sdp_transform-0.2.0.json_report.md
test/goldens/end2end/skiplist-0.1.0.json

Fill SDK constraint if mininum range is missing.

---

CHANGELOG.md
lib/src/package_analyzer.dart
test/end2end_test.dart
test/goldens/end2end/lints-1.0.0.json
test/goldens/end2end/lints-1.0.0.json_report.md

Fix tagging of asset-only packages.

---

CHANGELOG.md
lib/src/code_problem.dart
test/code_problem_test.dart

Do not block analysis on too many lines from dartanalyzer.

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/sdk_env.dart
lib/src/version.dart
pubspec.yaml

Use 'dart analyze' + local copy for analysis.

---

lib/src/sdk_env.dart

Explicit timeout while running dart analyze.

---

lib/src/version.dart
pubspec.yaml

Let's have a release with the analysis fixes out, the URL check can go into the next one.

Prepare release 0.19.1

---

CONTRIBUTING.md
lib/src/messages.dart
lib/src/report/static_analysis.dart
test/goldens/end2end/sdp_transform-0.2.0.json
test/goldens/end2end/sdp_transform-0.2.0.json_report.md
test/goldens/end2end/skiplist-0.1.0.json
test/goldens/end2end/skiplist-0.1.0.json_report.md

Related to https://github.com/dart-lang/dart_style/issues/986

Update Dart formatter message

---

lib/src/download_utils.dart

Use package:http's retry in download_utils.dart

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/package_context.dart
lib/src/sdk_env.dart
lib/src/version.dart
pubspec.yaml
test/self_run_test.dart

- Fix issue with git root directory detection: https://github.com/dart-lang/pana/issues/941#issuecomment-900325199
- Closes #946.
- Also use merged outputs in cases where it is likely to change in the future.
- Added self-run test with local path reference.

Follow-up fixes and future-proofing to runProc changes.

---

bin/license_detector_bin.dart
lib/src/license.dart
lib/src/license_detection/license_detector.dart
test/license_test.dart

- wrapped the loading code in async uri resolver
- also removed a debug code snippet

Load licenses through resource uri.

---

lib/src/third_party/diff_match_patch/.pubignore
pubspec.yaml

Publishing showed a few warnings.
This will clear them.

Fix publishing warnings

---

lib/src/third_party/diff_match_patch/test.dart

- removed tests that was running faster than expected
- fixed tests that had changing order

Remove minimum time test

---

CHANGELOG.md
lib/src/license_detection/license.dart
lib/src/version.dart
pubspec.yaml

Consistent license evaluation order to fix tests.

---

CHANGELOG.md
lib/src/sdk_env.dart
lib/src/utils.dart

- Fixes #949.
- also updated flutter version processing to use the same method

Better handling of JSON parsing issues in pub outdated.

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/tag/tagger.dart
lib/src/version.dart
pubspec.yaml
test/goldens/end2end/audio_service-0.17.0.json
test/goldens/end2end/url_launcher-6.0.3.json
test/tag/tag_end2end_test.dart

https://github.com/dart-lang/pub-dev/issues/5133

Tag Flutter plugins with is:plugin.

---

CHANGELOG.md
lib/src/tag/_graphs.dart

Fix thrown exception: using TagException.

---

CHANGELOG.md
lib/src/package_context.dart
pubspec.yaml
test/end2end_light_test.dart
test/golden_file.dart
test/goldens/end2end/async-2.5.0.json
test/goldens/end2end/async-2.5.0.json_report.md
test/goldens/end2end/audio_service-0.17.0.json
test/goldens/end2end/audio_service-0.17.0.json_report.md
test/goldens/end2end/dnd-2.0.0.json
test/goldens/end2end/dnd-2.0.0.json_report.md
test/goldens/end2end/sdp_transform-0.2.0.json
test/goldens/end2end/sdp_transform-0.2.0.json_report.md
test/goldens/end2end/skiplist-0.1.0.json
test/goldens/end2end/skiplist-0.1.0.json_report.md
test/goldens/end2end/webdriver-3.0.0.json
test/goldens/end2end/webdriver-3.0.0.json_report.md

For 8 months code problems have not been included in the pana report, resulting in all packages getting higher score for static analysis.
With this fix, these are included again. Hence, this change might result in score reduction for many packages on pub.dev.

Fix analysis: propagate code problems.

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml
test/ensure_build_test.dart

Root cause of the regression was https://github.com/dart-lang/pana/pull/998/files#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25R36

Fix build verify test and generated version.

---

CHANGELOG.md
bin/pana.dart

Change pana exit code when score is not within threshold.

---

CHANGELOG.md
lib/src/license.dart
lib/src/model.dart
lib/src/model.g.dart
lib/src/package_analyzer.dart
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json
test/goldens/end2end/async-2.5.0.json
test/goldens/end2end/audio_service-0.17.0.json
test/goldens/end2end/bulma_min-0.7.4.json
test/goldens/end2end/dnd-2.0.0.json
test/goldens/end2end/http-0.13.0.json
test/goldens/end2end/lints-1.0.0.json
test/goldens/end2end/mime_type-0.3.2.json
test/goldens/end2end/nsd_android-1.0.2.json
test/goldens/end2end/sdp_transform-0.2.0.json
test/goldens/end2end/skiplist-0.1.0.json
test/goldens/end2end/url_launcher-6.0.3.json
test/goldens/end2end/webdriver-3.0.0.json
test/license_test.dart

- #1015
- exposes score and multiple candidates if there are more than one
- doesn't change the algorithm or the thresholds

Expose multiple license detection.

---

CHANGELOG.md
lib/src/repository/git_local_repository.dart
lib/src/version.dart
pubspec.yaml

Also restricts `recurse-submodules`.

Cache the currently fetched depth in GitLocalRepository

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- populate the pubspec repository field

populate the pubspec repository field

---

lib/src/package_context.dart

- Follow-up to #1073.
- The try-catch block is a no-op.
- There is no point of checking `exitCode` > 0, we know it is != 0 already.

Code cleanup in dependency resolution.

---

.github/workflows/test-package.yml
lib/src/code_problem.dart
lib/src/package_context.dart
lib/src/sdk_env.dart
lib/src/utils.dart
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json
test/goldens/end2end/audio_service-0.18.4.json
test/goldens/end2end/audio_service-0.18.4.json_report.md
test/goldens/end2end/nsd_android-1.2.0.json
test/goldens/end2end/nsd_android-1.2.0.json_report.md
test/goldens/end2end/skiplist-0.1.0.json
test/goldens/end2end/url_launcher-6.1.2.json
test/goldens/end2end/url_launcher-6.1.2.json_report.md
test/report/dependencies_test.dart

- Fixes #1047.
- Supersedes: #1048, #1052.

Use pub outdated instead of pub upgrade.

---

lib/src/repository/check_repository.dart

Handle CheckedFromJsonException during repository verification.

---

lib/src/download_utils.dart

Fix how download URLs are calculated.

---

CHANGELOG.md
lib/src/model.dart
lib/src/model.g.dart
lib/src/package_analyzer.dart
lib/src/repository/check_repository.dart
pubspec.yaml
test/goldens/end2end/async-2.5.0.json
test/goldens/end2end/audio_service-0.18.4.json
test/goldens/end2end/url_launcher-6.1.2.json
test/goldens/end2end/webdriver-3.0.0.json

- https://github.com/dart-lang/pub-dev/issues/4476
- As the `CONTRIBUTING.md` file may be outside of the archive, we do the detection during the repository verification.
- Only valid URLs are exposed.

Detect 'CONTRIBUTING.md' during repositority verification and expose if URL check succeeds.

---

CHANGELOG.md
lib/src/references/pubspec_urls.dart

Lenient repository/homepage URL switch for packages that have no repository verification enabled.

---

CHANGELOG.md
lib/src/model.dart
lib/src/model.g.dart
lib/src/package_analyzer.dart
lib/src/version.dart
pubspec.yaml
test/end2end_test.dart
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json
test/goldens/end2end/async-2.5.0.json
test/goldens/end2end/audio_service-0.18.4.json
test/goldens/end2end/bulma_min-0.7.4.json
test/goldens/end2end/dnd-2.0.0.json
test/goldens/end2end/http-0.13.0.json
test/goldens/end2end/lints-1.0.0.json
test/goldens/end2end/mime_type-0.3.2.json
test/goldens/end2end/nsd_android-1.2.0.json
test/goldens/end2end/onepub-1.1.0.json
test/goldens/end2end/sdp_transform-0.2.0.json
test/goldens/end2end/skiplist-0.1.0.json
test/goldens/end2end/steward-0.3.1.json
test/goldens/end2end/url_launcher-6.1.2.json
test/goldens/end2end/webdriver-3.0.0.json

Summary.createdAt + extending the change method.

---

lib/src/download_utils.dart

Extra logging when the download fails.

---

lib/src/pubspec.dart
test/report/_tool_environment.dart
test/report/dependencies_test.dart

Fix of https://github.com/dart-lang/pana/issues/1173

Handle `>=2.x.0 <3.0.0` as `>=2.12.0 <4.0.0` for x>=12

---

CHANGELOG.md
lib/src/report/_common.dart
lib/src/version.dart
pubspec.yaml

Limit highlighted code snippet sizes in the report.

---

lib/src/package_analyzer.dart
lib/src/package_context.dart
lib/src/references/pubspec_urls.dart
lib/src/repository/check_repository.dart
test/report/dependencies_test.dart
test/report/documentation_test.dart
test/report/template_test.dart
test/screenshot_test.dart

- Currently shares URL problems and repository verification results.
- Added a new method to invoke multiple versions of the same package with shared context.

Shared analysis context/cache to analyze multiple versions efficiently.

---

CHANGELOG.md
lib/src/maintenance.dart
lib/src/report/documentation.dart
lib/src/version.dart
pubspec.yaml
test/goldens/end2end/nsd_android-1.2.0.json
test/goldens/end2end/nsd_android-1.2.0.json_report.md
test/report/documentation_test.dart
test/screenshot_test.dart

A matching change to https://github.com/dart-lang/pub-dev/pull/6345

Strict names in package layout checks.

---

test/crc32_test.dart

The tests are the same, but fewer lines go into the logs.

Reduce the test counts as it spams the logs.

---

lib/src/report/multi_platform.dart

https://github.com/dart-lang/pana/issues/1218

Fix paragraph separation in report

---

lib/src/tag/_specs.dart

https://github.com/dart-lang/pana/issues/1219

Include missing dart: libraries in analysis

---

CHANGELOG.md
lib/src/report/dart3_compatiblity.dart
lib/src/version.dart
pubspec.yaml

Use Dart 3 & Flutter 3.10 label for Flutter packages.

---

CHANGELOG.md
lib/pana.dart
lib/src/screenshots.dart
lib/src/version.dart
pubspec.yaml

Fix missing package:lints dependency and PanaProcessResult export.

---

bin/pana.dart

The error was very confusing:
```
> pana .
WARNING    Flutter SDK path was not specified, pana will use the default Dart SDK to run `dart analyze` on Flutter packages.
INFO       Running `/usr/local/google/home/sigurdm/.dvm/darts/3.1.0/bin/dart --version`...
INFO       Running `flutter --no-version-check --version --machine`...
INFO       Running `git rev-parse --show-toplevel`...
INFO       Unable to read pubspec.yaml
Exception: Couldn't read pubspec.yaml in /tmp/pana_NSMAIW/.. PathNotFoundException: Cannot open file, path = '/tmp/pana_NSMAIW/./pubspec.yaml' (OS Error: No such file or directory, errno = 2)
#0      pubspecFromDir (package:pana/src/pubspec_io.dart:18:5)
#1      PackageContext.pubspec (package:pana/src/package_context.dart:109:18)
#2      PackageAnalyzer._inspect …
```

Check for existence of pubspec.yaml before analyzing local folder

---

CHANGELOG.md
lib/src/tag/_specs.dart
lib/src/version.dart
pubspec.yaml

Add dart:ui_web as Flutter Web platform.

---

CHANGELOG.md
lib/src/report/template.dart
lib/src/version.dart
pubspec.yaml

- Fixes #1264.
- Keeps the empty file check.

Remove file size checks.

---

CHANGELOG.md
lib/src/utils.dart

Fixes https://github.com/dart-lang/pub-dev/issues/7149

Fix empty yaml parsing.

---

CHANGELOG.md
lib/src/tag/_specs.dart
lib/src/version.dart
pubspec.yaml

Add dart:ui_web to the Flutter SDK detection library list.

---

analysis_options.yaml
bin/batch.dart
bin/pana.dart
lib/src/analysis_options.dart
lib/src/batch/batch_compare_command.dart
lib/src/batch/batch_query_command.dart
lib/src/batch/batch_run_command.dart
lib/src/dartdoc/dartdoc_index.dart
lib/src/download_utils.dart
lib/src/license_detection/tokenizer.dart
lib/src/maintenance.dart
lib/src/messages.dart
lib/src/package_analyzer.dart
lib/src/package_context.dart
lib/src/report/dependencies.dart
lib/src/report/template.dart
lib/src/repository/check_repository.dart
lib/src/sdk_env.dart
lib/src/tool/run_constrained.dart
lib/src/utils.dart
test/end2end_test.dart
test/package_descriptor.dart
test/package_server.dart
test/pubspec_test.dart
test/repository/git_local_repository_test.dart
test/screenshot_test.dart

On the road to using `package:dart_flutter_team_lints` and safer code where `dynamic` isn't introduced accidentally :)

Continue cleanup of inferred dynamic

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/version.dart
pubspec.yaml

https://github.com/dart-lang/pub-dev/issues/7622

Do not emit package names in allDependencies with trivial syntax issues.

---

lib/src/version.dart
pubspec.yaml

Prepare 0.22.3

---

lib/src/batch/batch_model.g.dart
lib/src/dartdoc/dartdoc_index.g.dart
lib/src/dartdoc/pub_dartdoc_data.g.dart
lib/src/internal_model.g.dart
lib/src/model.g.dart

Seems something updated in our generators.

Rebuild generated code

---

CHANGELOG.md
lib/src/maintenance.dart
lib/src/version.dart
pubspec.yaml
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json
test/goldens/end2end/_dummy_pkg-1.0.0-null-safety.1.json_report.md

https://github.com/dart-lang/pub-dev/issues/7800

Recognize new example files in bin/

---

CHANGELOG.md
lib/src/analysis_options.dart
lib/src/version.dart
pubspec.yaml
test/analysis_options_test.dart

https://github.com/dart-lang/pub-dev/issues/7810

Enable macros experiment pass-through in analysis_options.yaml

---

lib/src/version.dart
pubspec.yaml
test/tag/dart_sdk_libraries_test.dart

Also fixes test that checks for new SDK libraries.

Prepare release.

---

CHANGELOG.md
lib/src/package_analyzer.dart
lib/src/version.dart
pubspec.yaml

This is needed for https://github.com/dart-lang/pub-dev/pull/8173

Allow inspectDir method to use a custom logger.

---

CHANGELOG.md
lib/src/sdk_env.dart

Use restricted analysis_options file also when formatting

---

CHANGELOG.md
lib/src/repository/git_local_repository.dart
lib/src/version.dart
pubspec.yaml
test/repository/git_local_repository_test.dart

Fixes https://github.com/dart-lang/pana/issues/1207

Always use posix conventions when validating paths for git show

---

CHANGELOG.md
lib/src/internal_model.dart
lib/src/internal_model.g.dart
lib/src/report/dependencies.dart

Do not list SDK packages in the outdated packages report.

---

lib/src/utils.dart

Do not try to copy ipc-daemon file used by git-fsmonitor.
